### ISSUE TITLE
loadPath  from a specific folder :

### ISSUE THREAD

**Issue by mezzouhri** [i18next/i18next-http-backend#1]
Hi,
I'm using i18next-http-backend to initialise my languages and i would like to know if the parameter 'loadPAth 'can point to a folder is in the 'src' sub-directory like the exemple :
`loadPath: 'src/languages/{{lng}}/{{ns}}.json'`

Think you for your help.

**Comment by adrai** [comment]
To achieve something similar you can define the i18next preload option and ns option: https://www.i18next.com/overview/configuration-options#languages-namespaces-resources
Beside that, this will not work, because this library is not only used in node.js but also in browser and Deno environments...
i.e. I have no idea how this would work in browser

**Comment by adrai** [comment]
you can solve this i.e. like this:

```js
const { join } = require('path')
const { readdirSync, lstatSync } = require('fs')
const i18next = require('i18next')
const Backend = require('i18next-http-backend')
i18next
  .use(Backend)
  .init({
    // debug: true,
    lng: 'en',
    fallbackLng: 'en',
    preload: readdirSync(join(__dirname, '../locales')).filter((fileName) => {
      const joinedPath = join(join(__dirname, '../locales'), fileName)
      const isDirectory = lstatSync(joinedPath).isDirectory()
      return isDirectory
    }),
    ns: 'backend-app',
    defaultNS: 'backend-app',
    backend: {
      loadPath: join(__dirname, '../locales/{{lng}}/{{ns}}.json')
    }
  })
```

**Comment by adrai** [comment]
btw: if you're able to have fs access, probably this plugin is better: https://github.com/i18next/i18next-node-fs-backend

**Comment by mezzouhri** [comment]
Thank you so much,
I finally found the right conf in the link [https://www.i18next.com/overview/configuration-options#languages-namespaces-resources](url) you gave me
Thank you

```
import enTranslation from './en.json';
import frTranslation from './fr.json';
import arTranslation from './ar.json';

const resources = {
  en: {
    translation: enTranslation,
  },
  fr: {
    translation: frTranslation,
  },
  ar: {
    translation: arTranslation,
  },
};

i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: 'en',
    fallbackLng: 'en',
    //preload: ['en', 'fr', 'ar'],
    debug: process.env.NODE_ENV === 'development',

    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
    },
  });`
```

**Comment by adrai** [comment]
Ah, ok you are using react-i18next...
this is ok, this way you are bundling all translations with the app.

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.
If you liked my support / work - I would enjoy a coffee sponsored using the “💜Sponsor Button”.
There are many ways to help this project 🙏

**Comment by jamuhl** [comment]
@mezzouhri you can use the backend -> just be aware in react-script webpack by default serves all files contained in the public folder (and bundles those for prod) -> so during production and development all in /public/ is accessible (so also the default path in the backend)...moving those translations to /src/ you will have make sure those files get added to final output folder and are hosted during development....

**Comment by adrai** [comment]
example: https://github.com/i18next/react-i18next/tree/master/example/react

**Comment by mezzouhri** [comment]
> Ah, ok you are using react-i18next...
> this is ok, this way you are bundling all translations with the app.

@adrai  yes, I'm using it whit react app, 




> @mezzouhri you can use the backend -> just be aware in react-script webpack by default serves all files contained in the public folder (and bundles those for prod) -> so during production and development all in /public/ is accessible (so also the default path in the backend)...moving those translations to /src/ you will have make sure those files get added to final output folder and are hosted during development....

@jamuhl Thank you for the explanation, it's now clear for me why we add the languages src to the public folder
