### ISSUE TITLE
Version 2.0.0 breaks reloadResources

### ISSUE THREAD

**Issue by medihack** [i18next/i18next-http-backend#101]
## 🐛 Bug Report

After upgrading to Version 2.0.0 (also just tried 2.0.1) the i18next instance still contains the old data after calling `reloadResources` and the promise is resolved. The data is correctly fetched from the server (my API route is hit), but the store isn't updated anymore. Works without a problem with v1.4.5.

## To Reproduce

```
// also doesn't work when using the callback
i18next.reloadResources(lng, ns).then(() => {
  console.log(i18next.store) // still contains the old data
})

```
## Expected behavior

The store should be correctly updated.

## Your Environment

- *runtime version*: Chrome, Next.js 12
- *i18next version*: 22.0.4
- *os*: Linux (Gitpod)

**Comment by adrai** [comment]
v2.0.0 was just a typescript change...
Can you please provide a minimal reproducible example?

**Comment by adrai** [comment]
btw: just tested it based on this example: https://github.com/i18next/i18next-http-backend/tree/master/example/node and seems to work as expected

**Comment by medihack** [comment]
Ok, that's strange then. The only other thing I did is to get rid of the `i18next-multiload-backend-adapter` as I thought it isn't necessary anymore.

This is the old way I set it up (v1.4.5):
```
import i18next, { InitOptions } from "i18next"
import HttpBackend from "i18next-http-backend"
import BackendAdapter from "i18next-multiload-backend-adapter"
import { defaultConfig } from "./i18nDefaultConfig"

export const createClient = (config: InitOptions) => {
  const instance = i18next.createInstance()

  // TODO: fix types, see https://github.com/i18next/i18next-fs-backend/issues/20
  const backend = {
    backend: HttpBackend,
    backendOption: {
      loadPath: "/api/locales?lng={{lng}}&ns={{ns}}",
    },
  } as any

  const initPromise = instance.use(BackendAdapter).init({
    ...defaultConfig,
    backend,
    ...config,
  })

  return { i18n: instance, initPromise }
}
```

And this the new way (v2.0.1):
```
import i18next, { InitOptions } from "i18next"
import HttpApi from "i18next-http-backend"
import { defaultConfig } from "./i18nDefaultConfig"

export const createClient = (config: InitOptions) => {
  const instance = i18next.createInstance()

  const initPromise = instance.use(HttpApi).init({
    ...defaultConfig,
    backend: {
      allowMultiLoading: true,
      loadPath: "/api/locales?lng={{lng}}&ns={{ns}}",
    },
    ...config,
  })

  return { i18n: instance, initPromise }
}
```

Can it be that multiloading is the problem?
If things are still unclear I can try to setup a minimal example.

**Comment by adrai** [comment]
Adapter is still needed to enable MultiLoading https://github.com/i18next/i18next-multiload-backend-adapter

https://github.com/i18next/i18next-http-backend#backend-options
<img width="942" alt="image" src="https://user-images.githubusercontent.com/1086194/199482586-8ddbe915-1ac7-4168-818f-4314ab20954a.png">

**Comment by medihack** [comment]
Ok, I see. Sorry for wasting your time :-( Never thought of that as refreshing the page showed everything correctly because of SSR. I wait for the 2.0.0 npm release of i18next-multiload-backend-adapter and bring it back in. Thanks a lot for your help and all the work you put into i18next! Closing this issue for now.
