### ISSUE TITLE
`CallbackError` is incorrectly set as a `string` value

### ISSUE THREAD

**Issue by jonkoops** [i18next/i18next-http-backend#102]
## 🐛 Bug Report

The value passed for `CallbackError` is incorrect. According to the [type definition](https://github.com/i18next/i18next/blob/abb7651a7cbf5a8dffe7b2557f5e42555193e15d/index.d.ts#L1006) it can only be of type `Error | null | undefined`, but in the code it's also being passed as a `string` in [multiple occasions](https://github.com/i18next/i18next-http-backend/blob/8616dc57cd3842a3f9fdffc9bd09e726bca6c8e0/lib/index.js#L70).

## Expected behavior

In the aforementioned cases the value should be passed as the type `Error`.

**Comment by adrai** [comment]
can you try with i18next v22.0.6 ?

**Comment by jonkoops** [comment]
Yeah, that works. But should the fix not be that it is always an instance of `Error`? Also this is a breaking change to the types as folks might not be checking for `string` values at this time.

For example:

```ts
const callback: MultiReadCallback = (err, data) => {
   if (err) {
     // This will now be a TypeScript error, as 'message' does not exist on type 'string'
     console.log(err.message)
   }
}
```

**Comment by adrai** [comment]
no, it was a string since the beginning: https://github.com/i18next/i18next-http-backend/commit/767e0b6d4946477450a3f0c07bd79812a2490cdd#diff-92bbac9a308cd5fcf9db165841f2d90ce981baddcb2b1e26cfff170929af3bd1R65
