### ISSUE TITLE
fallback locale when fetching API endpoint failed or error

### ISSUE THREAD

**Issue by phatify** [i18next/i18next-http-backend#108]
## 🚀 Feature Proposal

Please add feature fallback locale when fetching API endpoint failed or error. 
For example I have a config like this:
```
...
loadPath: `${process.env.INTERNAL_API_URI}/api/locales/{{lng}}/{{ns}}`
...
```

When fetching data failed I want to set a fallback locale default from `/public/en/common`.

**Comment by jamuhl** [comment]
fallback is handled by i18next https://www.i18next.com/principles/fallback#language-fallback not the backend

**Comment by jamuhl** [comment]
did you read the link provided...there is no need to handle this in the backend as i18next core takes care of this for all backend implementations

**Comment by adrai** [comment]
https://github.com/i18next/i18next-http-backend/tree/master/example/next
