### ISSUE TITLE
Expected identifier, string or number

### ISSUE THREAD

**Issue by ishamshur** [i18next/i18next-http-backend#11]
After installing this plugin, an error occurs in IE/Edge.
I connect this plugin like this:

`import i18next from 'i18next';
import HttpApi from 'i18next-http-backend';

i18next
  .use(HttpApi)
  .init({
     lng: 'ru',
     fallbackLng: 'ru',
    backend: {
            loadPath: staticUrl + '/locales/{{lng}}/{{ns}}.json'
        }
  });`

I use webpack and babel:

`module: {
        rules: [
            {
                test: /\.jsx?$/,
                exclude: /node_modules/,
                loader: 'babel-loader',
                options: {
                    presets: [
                        "@babel/preset-env",
                        "@babel/preset-react",
                    ],
                    plugins: [
                        "@babel/plugin-proposal-function-bind",
                        "@babel/plugin-proposal-class-properties",
                        "@babel/plugin-transform-spread",
                        "@babel/plugin-proposal-object-rest-spread"
                    ],
                    cacheDirectory: true
                }
            }
        ]
    },`

![Edge](https://user-images.githubusercontent.com/20657148/81948966-f7d51e00-960a-11ea-8ef9-6a92e8c5bb49.png)
![Edge2](https://user-images.githubusercontent.com/20657148/81949550-a6795e80-960b-11ea-8ded-d87f6be5e746.png)

**Comment by adrai** [comment]
seems you are excluding node_modules (where this module probably is installed too.

**Comment by ishamshur** [comment]
Yes, I have this line:
exclude: /node_modules/
How can this be fixed?

**Comment by adrai** [comment]
It depends on your project...
Why have you excluded  the node_modules?
You need to figure this out on your own... sorry.

**Comment by adrai** [comment]
Can you create a reproducable repo... so I can also have a look at it?

**Comment by adrai** [comment]
Btw: does this occur only in IE?

**Comment by ishamshur** [comment]
The problem was solved like this:
{
    test: /\.jsx?$/,
    exclude: /node_modules\/(?!(i18next\-http\-backend)\/).*/,
    loader: 'babel-loader',
    options: {
        presets: [
            "@babel/preset-env",
            "@babel/preset-react",
        ],
        plugins: [
            "@babel/plugin-proposal-function-bind",
            "@babel/plugin-proposal-class-properties",
            "@babel/plugin-transform-spread",
            "@babel/plugin-proposal-object-rest-spread"
        ],
        cacheDirectory: true
     }
}

**Comment by adrai** [comment]
ok, thank you

**Comment by ishamshur** [comment]
> Btw: does this occur only in IE?

Yes, the problem was only in IE
