### ISSUE TITLE
Add language to `customHeaders` parameter

### ISSUE THREAD

**Issue by michalvadak** [i18next/i18next-http-backend#115]
## 🚀 Feature Proposal
Provide language to `customHeaders` parameter in options to be able to append it to `Accept-language` header.

## Example

```
customHeaders: (lng) => ({
        'Accept-language': lng,
})
```

**Comment by michalvadak** [comment]
The `i18next-http-backend` isn't sending the `Accept-language` header by default... 

I'm talking about the `options` parameter

**Comment by adrai** [comment]
Not the i18next-http-backend modules sets that header, but your browser will do it.
Check the network tab in your browser's dev tools and inspect the request.

**Comment by michalvadak** [comment]
Yeah okay... now it's there but the language is incorrect 
<img width="1459" alt="image" src="https://github.com/i18next/i18next-http-backend/assets/53196310/df042e14-7da6-410e-849a-0366af493f8d">

**Comment by adrai** [comment]
The language there is, the configured language of your browser... This is not an i18next topic sorry.
