### ISSUE TITLE
Value for reloadInterval?

### ISSUE THREAD

**Issue by sernaferna** [i18next/i18next-http-backend#116]
## Documentation issue

The documentation doesn't make it clear what value should be passed to the `reloadInterval` configuration. I assume it should either be seconds or milliseconds, but am not sure which.

## Motivation

It is already clear that the configuration accepts an interval or false, it just isn't clear whether the numeric value should be seconds, milliseconds, or something else. One option for defaulting the value is `60 * 60 * 1000` so I assume that means milliseconds.

**Comment by adrai** [comment]
Yes, milliseconds.
