### ISSUE TITLE
Module not found: Can't resolve 'encoding' in '.../node_modules/node-fetch/lib'

### ISSUE THREAD

**Issue by michalvadak** [i18next/i18next-http-backend#118]
## 🐛 Bug Report

When using `18next-http-backend` with NextJS 13 the console is throwing this error.

```
Module not found: Can't resolve 'encoding' in '.../node_modules/node-fetch/lib'
Import trace for requested module:
../../node_modules/node-fetch/lib/index.js
../../node_modules/cross-fetch/dist/node-ponyfill.js
../../node_modules/i18next-http-backend/esm/getFetch.cjs
../../node_modules/i18next-http-backend/esm/request.js
../../node_modules/i18next-http-backend/esm/index.js
../../libs/shared/feature/localization/src/lib/server.ts
../../libs/shared/feature/localization/src/server.ts
./app/[lng]/layout.tsx
```

## To Reproduce

Create NextJS 13 with app directory and setup i18next with i18next-http-backend

## Temporary workaround

```js
yarn add -D encoding
```

## Your Environment

- *i18next version*: 23.2.8
- *i18next-http-backend version*: 2.2.1
- *next version*: 13.4.12

**Comment by adrai** [comment]
Can you please provide a minimal reproducible example?
Are you using it on client side or on server side?

**Comment by adrai** [comment]
Seems to be a Next.js specific problem: https://github.com/vercel/next.js/issues/7621

**Comment by adrai** [comment]
There's not much we can do here, sorry.
