### ISSUE TITLE
loadPath arguments in custom request function

### ISSUE THREAD

**Issue by mi-col** [i18next/i18next-http-backend#120]
## 🚀 Feature Proposal

I would like to be able to have arguments of the `loadPath` function available as parameters in the `request` function.

## Motivation

In the case of unusual or strict APIs that don't fall under the url that can be constructed via the `loadPath` function, I would like to have its arguments be passed into the custom `request` function so that I can manage any scenario specific to the localization API that I am using.

## Example

In case the API I am using has strict requirements on multiple namespaces being passed in query params as `namespace=first&namespace=second` rather than `ns=first+second`, if I retrieve different locales from different APIs or any other unusual scenario requiring a fine-tuned approach.

**Comment by adrai** [comment]
Currently that's the only way. But If there are more users requesting this, we might do something...

**Comment by mi-col** [comment]
No problem, thanks for clarifying
