### ISSUE TITLE
Possibility to add timeout to the setup

### ISSUE THREAD

**Issue by simonbergstrom** [i18next/i18next-http-backend#123]
## 🚀 Feature Proposal

Add the possibility to add timeout for fetching i18n resource like the axios config `timeout`. (See example here for timeout: 
https://axios-http.com/docs/req_config and search for timeout)

## Motivation

When fetching i18n resource it would be really good to specify for how long a request is acceptable to wait for before fallbacking to fetching i18n resources from somewhere else. 

## Example

https://axios-http.com/docs/req_config and search for timeout

```
...i18n config
 backend: {
          backends: [HttpBackend, resourcesToBackend(config.resources)],
          backendOptions: [
            {
              loadPath: <URL_TO_FETCH>,
              crossDomain: true,
              timeout: 2000, // Will fallback to fetch i18n resources from file if request take more than 2 sec
            },
          ],
        },

```

**Comment by adrai** [comment]
You can already do so by specifying your own fetch/request function: https://github.com/i18next/i18next-http-backend#backend-options
