### ISSUE TITLE
Initial fetch call on vite serve mode

### ISSUE THREAD

**Issue by constantineMelios85** [i18next/i18next-http-backend#124]
## 🐛 Bug Report

I have a  react app for years now that I use i18next http backend for my translations. 
Recently I wanted to move from CRA to vite. 

The issue is that on vite serve seems like no call is made from the backend, unless I config a reload interval. After the reload if I trigger a HMR change to my app the translations are shown until an app refresh.

When I build the app and deploy it the backend works as expected.

```js
i18n
  .use(Backend)
  .use(initReactI18next)
  .init({
    react: {
      useSuspense: false,
    },
    debug: false,
    lng: 'en',
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
    },
    backend: {
      loadPath: '../locales/{{lng}}/{{ns}}.json',
      requestOptions: {
        cache: 'no-store',
      },
    },
  });
 

## Expected behaviour

Backend make the initial fetch call for translations.

## Your Environment

- *runtime version*: node v18.13.0, chromium browser
- *i18next version*: 23.6.0
- *os*: Mac
- *any other relevant information*

**Comment by adrai** [comment]
Can you please provide a minimal reproducible example. I suspect this is not directly related to i18next.

**Comment by constantineMelios85** [comment]
Yes you are right the problem was created cause to an i18next instance coming form another library.
