### ISSUE TITLE
Module '"i18next-http-backend"' has no exported member 'RequestCallback'.

### ISSUE THREAD

**Issue by kpawelczak** [i18next/i18next-http-backend#125]
## 🐛 Bug Report

In my Angular project I use custom request - https://github.com/i18next/i18next-http-backend?tab=readme-ov-file#backend-options. After updating to version 2.4.1, I get an error that the type `RequestCallback` is not exported. 

> Module '"i18next-http-backend"' has no exported member 'RequestCallback'.

If I change the import to `"i18next-http-backend/cjs" `it does not complain and it works. Would be nice if we could get access to this type from esm module.

## To Reproduce

```js
import type {
  HttpBackendOptions,
  RequestCallback,
} from 'i18next-http-backend';

const request = (
      options: HttpBackendOptions,
      url: string,
      payload: string | object,
      callback: RequestCallback
    ) => {
    }

```

## Expected behavior

`RequestCallback` can be imported from `i18next-http-backend`

## Your Environment

- *runtime version*: node v18
- *i18next version*: 2.4.1
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by adrai** [comment]
Try with v2.4.2

**Comment by kpawelczak** [comment]
thanks, it works now. Really appreciate the fast response.
