### ISSUE TITLE
have fetch pluggable

### ISSUE THREAD

**Issue by jacobbogers** [i18next/i18next-http-backend#132]
Hi, Can you expose the "fetch" as pluggable, this would help greatly at testing especially as we dont use jest mocks (we use `it.concurrent` extensively will be an issue since jest mocks are global to test file) 

hence the need to make it pluggable per `it` test

Example (just spitballing): 
```js
config: { 
    getFetch: () => globalThis.fetch
}
```

for mocking (integration  tests)

```js
config: { 
    getFetch: () => fetchMocked
}
```

**Comment by adrai** [comment]
If you know of a way that works without breaking in all current environments (client, server, Node.js, Deno, etc.) feel free to open a PR

**Comment by jacobbogers** [comment]
Thanks for your understanding, let me see if I can cook something up.

**Comment by adrai** [comment]
btw: I would prefer to not add additional complexity, since you can also pass your custom request function here: https://github.com/i18next/i18next-http-backend?tab=readme-ov-file#backend-options

<img width="808" alt="image" src="https://github.com/i18next/i18next-http-backend/assets/1086194/08285b4c-5436-44ec-bc68-8069b14a4011">

**Comment by jacobbogers** [comment]
I made a PR

https://github.com/i18next/i18next-http-backend/pull/133

**Comment by jacobbogers** [comment]
To answer your question about `request`

Sure we can use `request` , but our test regiment is to simulate at lowest level possivle, (the actual network traffic and especially simulating errors, checking headers, or sending back incomplete data, delays, etc, etc) and see if our apps can deal with this situation prorperly. 


> btw: I would prefer to not add additional complexity, since you can also pass your custom request function here: https://github.com/i18next/i18next-http-backend?tab=readme-ov-file#backend-options
> 
> <img alt="image" width="808" src="https://private-user-images.githubusercontent.com/1086194/306412872-08285b4c-5436-44ec-bc68-8069b14a4011.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MjY5NDksIm5iZiI6MTcwODUyNjY0OSwicGF0aCI6Ii8xMDg2MTk0LzMwNjQxMjg3Mi0wODI4NWI0Yy01NDM2LTQ0ZWMtYmM2OC04MDY5YjE0YTQwMTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjFUMTQ0NDA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjU4ZmMxMTdjNmUxYTc1ZWJjNDY5ZTI0MjVjZTVlNjhjYzhmNWVjNTA2M2NkYTE5MmNmNzQzYWRhM2I4ZDYyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IBTPPTcMY2V5RkOK1Jbl1WDprVQzazGNOwkk5gZ9AwA">
