### ISSUE TITLE
cross-fetch leaks to client-side bundle

### ISSUE THREAD

**Issue by felixmosh** [i18next/i18next-http-backend#136]
## 🐛 Bug Report

`cross-fetch` is ment to be use only in node env (based on the code [here](https://github.com/i18next/i18next-http-backend/blob/master/lib/getFetch.cjs#L13)), but when I bundle a client app, this lib is inside the bundle.

## To Reproduce

https://pzz539.csb.app/

You can search for cross-fetch in the chrome devtools you will see that it's get bundled.

![image](https://github.com/i18next/i18next-http-backend/assets/9304194/0f5ca1c9-c25e-42a8-9221-98f258581f7c)

## Expected behavior

It should be striped from the browser envs

The problem is in that if condition, bundlers usually replacing `typeof window` with `"object"` for browser env (atleast Next.js does), so the deopt of this optimization is the second `or` condition `typeof window.document === 'undefined'`
```js
if (typeof require !== 'undefined' && (typeof window === 'undefined' || typeof window.document === 'undefined')) {
  var f = fetchApi || require('cross-fetch')
  if (f.default) f = f.default
  exports.default = f
  module.exports = exports.default
}
```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by adrai** [comment]
landed in v2.5.1
