### ISSUE TITLE
Have a way to handle errors

### ISSUE THREAD

**Issue by eMerzh** [i18next/i18next-http-backend#138]
Hello, 

It seems that for some reasons, sometimes, we can't load the translations, 

## 🚀 Feature Proposal

it's nice to be able to manage the loading error with some kind of callback
like onError with url, error ?

## Motivation

To be able to debug why client can't load stuff, without completely customizing the request or lib

**Comment by eMerzh** [comment]
oh thanks ... is the debug mandatory? because i would like to enable that on prod using tools like sentry

**Comment by adrai** [comment]
no it's not mandatory
