### ISSUE TITLE
Problem loading new language on iOS (React Ionic)

### ISSUE THREAD

**Issue by daniosoriov** [i18next/i18next-http-backend#156]
## 💥 Regression Report

When changing languages on our Ionic React application, we experience an idling state of about 15 seconds on iOS before switching the language.

## Last working version

Worked up to version: 2.6.1

Stopped working in version: 2.6.2

## To Reproduce

```tsx
import i18next from 'i18next'

// Load the current selected language, format: `en-GB`
const { selectedLanguage } = useSelector((state: AppState): RegionState => state.region)
i18next.changeLanguage(selectedLanguage)
```

We do not see any relevant console logs or error messages.

## Expected behavior

Before, it would load the new language immediately. Now, it takes about 15 seconds. Notice that this happens only on iOS. We also deploy on Android and as a PWA and have no issues there.

## Your Environment

- *runtime version*: node v20.17.0.
- *i18next version*: 23.16.0
- *os*: iOS and mac

P.S.: We can provide a quick video where the behaviour is seen clearly if you need it.

**Comment by adrai** [comment]
Probably same story like https://github.com/i18next/i18next-http-backend/issues/154

Probably the resources loading is failing (and was already failing before), but now it reties a couple of times before finishing the init call....

**Comment by daniosoriov** [comment]
> Probably same story like #154
> 
> Probably the resources loading is failing (and was already failing before), but now it retries a couple of times before finishing the init call....

Yes, it may be the same problem.
