### ISSUE TITLE
Version 2.7.0 introduced a breaking change - top-level await. Changelog says it should have been released as 3.0.0

### ISSUE THREAD

**Issue by Platonn** [i18next/i18next-http-backend#161]
## 🐛 Bug Report

After installing the latest v2.7.0 (released ~18h ago), while building an Angular app in a mode that doesn't support top-level await, I'm getting an error:
```
Application bundle generation failed. [9.305 seconds]
✘ [ERROR] Top-level await is not available in the configured target environment ("chrome129.0", "edge129.0", "firefox115.0", "ios17.0", "safari17.0" + 5 overrides)
  node_modules/i18next-http-backend/esm/request.js:83:16:
   83 │   fetchApi = (await import('cross-fetch')).default;
```

## Expected behavior

Ideally such a breaking change shouldn't land in a minor release, but only a major.
I can see in the changelog https://github.com/i18next/i18next-http-backend/blob/8d8bf8d/CHANGELOG.md there is no mention about 2.7.0 but only 3.0.0.

So I guess it was meant to be released as a major.

If yes, I guess 2.7.0 should be [unpublished withing 72h from the release](https://docs.npmjs.com/unpublishing-packages-from-the-registry) from NPM? Or a patch 2.7.1 (with a revert of the latest commit) should be released? - more safe option IMHO. 

PS. Many thanks for your library 🙌

**Comment by Chousse** [comment]
yep pretty same behavior with a webpack compilation : 
`WARNING in ./node_modules/i18next-http-backend/esm/request.js
The generated code contains 'async/await' because this module is using "topLevelAwait".
However, your target environment does not appear to support 'async/await'.
As a result, the code may not run as expected or may cause runtime errors.`

**Comment by brtvcl** [comment]
Downgrading to `2.6.2` worked for me as a temporary solution

**Comment by HammadMomin** [comment]
![image](https://github.com/user-attachments/assets/c3120d04-b6ad-46cc-a446-3760428794c2)
i am also facing the same issue already tried downgrading to version `2.6.2` buts its not helping and even tried 3.0.0 but its not resolved, any temp resolution for this please let me know

**Comment by Platonn** [comment]
I can see now the version 2.7.0 has been **[unpublished](https://www.npmjs.com/package/i18next-http-backend/v/1.0.10?activeTab=versions)** just now. So no longer a problem for us.
![image](https://github.com/user-attachments/assets/e9157368-7fa1-4a3e-82d8-0069ecf89216)

**Comment by adrai** [comment]
> I can see now the version 2.7.0 has been **[unpublished](https://www.npmjs.com/package/i18next-http-backend/v/1.0.10?activeTab=versions)** just now. So no longer a problem for us. ![image](https://private-user-images.githubusercontent.com/4001059/388454340-e9157368-7fa1-4a3e-82d8-0069ecf89216.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODM1ODksIm5iZiI6MTczMjE4MzI4OSwicGF0aCI6Ii80MDAxMDU5LzM4ODQ1NDM0MC1lOTE1NzM2OC03ZmExLTRhM2UtODJkOC0wMDY5ZWNmODkyMTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjFUMTAwMTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWVkYTQwZjVjMmE5ZGY0MTRiNmMxOGZjMmIzZTZkMDVhNWZiNWQzNjBjNWM2YmMwNTcwMDU1NThkNmUwZjY3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.1VATqvSePTgXrcuvEVqWbuklCdSwXbJ5umitect-xGA)
> 
> Many thanks the library maintainers, for a quick reaction 🙌

fyi: v2.7.0 was deprecated a couple of hours ago

**Comment by Platonn** [comment]
No worries at all. Many thanks again for your quick help 🙌

**Comment by Explorer-Carbon** [comment]
> fyi: v3.0.1 tries to remove the top-level await - if someone wants to try...

v3.0.1 runs without issues with vite@5.4.11 using the default build target (Chrome 87).

**Comment by akshaybachhav** [comment]
Module format cjs does not support top-level await. Use the "es" or  "system" output formats rather. at error...

we have got this error while the project using dependencies mentioned got th error  i18next-http-backend 
after changing the version 2.7.0 to 3.0.1 the issue got resolved.

**Comment by jamalsoueidan** [comment]
I'm running 3.0.1 and still an issue with react-router v7, how did you manage to fix this?

    "i18next": "^24.2.0",
    "i18next-browser-languagedetector": "^8.0.2",
    "i18next-fs-backend": "2.4.0",
    "i18next-http-backend": "^3.0.1",
    

✔ 23:51:15 Convex functions ready! (5.37s)
X [ERROR] Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)

    node_modules/i18next-fs-backend/esm/readFile.js:7:20:
      7 │ var fs = !isDeno ? (await import('node:fs')).default : undefined;
        ╵                     ~~~~~

X [ERROR] Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)

    node_modules/i18next-fs-backend/esm/writeFile.js:7:20:
      7 │ var fs = !isDeno ? (await import('node:fs')).default : undefined;

**Comment by jamalsoueidan** [comment]
I also tried with 2.6.2 same issue.

**Comment by jamalsoueidan** [comment]
> Downgrading to `2.6.2` worked for me as a temporary solution

I tried with 2.6.2 same issue.
