### ISSUE TITLE
How to write missing translations to file?

### ISSUE THREAD

**Issue by pylipp** [i18next/i18next-http-backend#163]
Sorry about cross-posting from SO. [My post from last week](https://stackoverflow.com/questions/79268666/how-to-write-missing-translations-to-file) didn't get any replies.

## Documentation issue

in my React app I have i18n configured like this:

```js
import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import HttpApi from 'i18next-http-backend';

i18n
  .use(HttpApi)  // load translation using http -> see /public/locales
  .use(initReactI18next)
  .init({
    lng: "en",
    debug: true,
    fallbackLng: "en",
    saveMissing: true,
    backend: { addPath: 'http://localhost:3000/public/locales/{{lng}}/{{ns}}.missing.json'},
    interpolation: {
      escapeValue: false // react already safes from xss
    }
  });
```
Now when I add new untranslated text to my app, be it `{t("find_box")}`, I can see in the browser console that a POST request is being issued to the `addPath`:

```
{
	"POST": {
		"scheme": "http",
		"host": "localhost:3000",
		"filename": "/public/locales/en/translation.missing.json"
	}
}
```
with the response body `{"find_box": "find_box"}`. The request returns a 200.

I understood the `saveMissing` feature that the untranslated entry would be added to the file at `addPath`. But that doesn't happen. The file at `addPath` exists and contains an empty object `{ }`.

1. Is my assumption about the `saveMissing` feature correct?
2. Do I need a custom [`missingKeyHandler`](https://www.i18next.com/overview/configuration-options#missing-keys) to write the content of the POST request to file?
3. I locally run the React app via docker-compose, does that make a difference?

**Comment by pylipp** [comment]
@adrai thanks for the reply, I understand better now.

Do I assume correctly that i18next-http-middleware works with a JS backend only?
I want to use i18next in a React front-end without a JS back-end (our webapp has a Python back-end).

**Comment by adrai** [comment]
Yes it work for JS only.
