### ISSUE TITLE
{{lng}} in `loadPath` returns only 2-letter language code instead of BCP-47 code

### ISSUE THREAD

**Issue by billomore** [i18next/i18next-http-backend#164]
## 🐛 Bug Report

In `loadPath` url template, the `{{lng}}` template var only contains the 2-letter language code instead of the full BCP-47 tag.

My translation folder structure follows the BCP-47 standard, so the URL produced by processing the template string turns out broken

## To Reproduce
In the following config example,  only get `en` inside the `loadPath` instead of `en-GB`:
```js
i18next
    .use(initReactI18next)
    .use(ChainedBackend)
    .init({
        lng: 'en-GB',
        contextSeparator: '|',
        interpolation: {
            escapeValue: false, // react already safes from xss => https://www.i18next.com/translation-function/interpolation#unescape
        },
        ns: ['myns1', 'myns2', 'megans'],
        backend: {
            backends: [
                resourceToBackend(resources), // my locally stored translations
                HttpBackend, // fallback
            ],
            backendOptions: [{}, { loadPath: `/translations/{{lng}}/{{ns}}.json` }],
            // same happens if I pass a fuction)
            // backendOptions: [{}, { loadPath: (lng, ns) => `translations/${lng}/${ns}.json` }],
        },
    });
```
i.e. `/translations/{{lng}}/{{ns}}.json` produces `/translations/en/myns1.json`

## Expected behavior

To get `en-GB` as `{{lng}}`. 

Do I miss something here? Dug through the docs and issues, but found nothing on the matter

## Your Environment

- *runtime version*: node v20, react native
- *i18next version*: i.e. 23.16.0
- *os*: Mac

**Comment by adrai** [comment]
That's not related to the loadPath, but probably because of your language detector and/or your load option: https://www.i18next.com/overview/configuration-options

Please provide a minimal reproducible example repository that shows your issue, not just code snippets.

**Comment by jamuhl** [comment]
or it's the normal loading behaviour loading `en-US` + `en` + `fallbackLng` https://www.i18next.com/principles/fallback#variant-resolving-fallback-from-dialects-or-scripts , https://www.i18next.com/principles/translation-resolution#languages , ...

**Comment by billomore** [comment]
@adrai `load` option was my culprit; despite me having only one language, its default `all` cut the locale part of the language code. Set it to `load: 'currentOnly'` and it sorted out :) Thank you for the quick response!
