### ISSUE TITLE
Format of backend response

### ISSUE THREAD

**Issue by jamiechong** [i18next/i18next-http-backend#18]
I'm trying to use the backend to fetch from a backend I don't control. The endpoint contains the translations of ALL languages. I'm trying to use the `parse` callback to translate the data returned from the backend into something this plugin understands. 

What is the expected format of the return value of `parse`?

**Comment by jamuhl** [comment]
In your case also have a look at: https://github.com/i18next/i18next-multiload-backend-adapter

**Comment by adrai** [comment]
This is the default for the parse function: ‘parse: data => JSON.parse(data)’

But like suggested, multiload should be what you are looking for.
