### ISSUE TITLE
i18n load translations from s3bucket

### ISSUE THREAD

**Issue by hyprstack** [i18next/i18next-http-backend#20]
I am using the `i18n` module in my react app which is hosted as an app (which I will refer to as live app) on `S3` and has `cloudfront` sitting in front of it.

I want to store the s3 url in a config file as to avoid having it hardcoded in my app so that I can work against translation files stored locally in the `public/locales` folder when I'm developing.

Initially I had my backend options set-up so that it would always try and look up the files in the `locales` path. And this worked locally but stopped working on S3 although the locales folder was present in the S3 bucket. I also noticed that no request was being sent from the app to retrieve the translation files.

```
backend: {
    loadPath: 'locales'
  }
```

I then decided to upload the translation files to another S3 bucket and host them there to see if this would fix the issue.
I changed my config to hardcode the s3 bucket path. This worked both locally and on the live app. But this means that I can't use my config file to determine the loadPath option.

```
 backend: {
    loadPath: '<myhardcoded-s3-bucket-url>/{{lng}}/translation.json',
    crossDomain: true
  }
```

I then thought I could construct the url in place as so:
```
/*global AWS_CONFIG */
/*eslint no-undef: "error"*/
...
...
...
backend: {
    loadPath: `${AWS_CONFIG.aws_app_translations_path}/{{lng}}/translation.json`,
    crossDomain: true
  }
```

Strangely again this worked locally when `AWS_CONFIG.aws_app_translations_path` was both `http://localhost:3000/locales` and `<myhardcoded-s3-bucket-url>`.
However once I pushed it live, it failed again. This time making a request to `https://<my-apps-base-path>/undefined/en-GB/translation.json` for example. So it's trying to use the app path and append why I have defined in `loadPath`.

I then saw that I could have `loadPath` as a function to construct my url. This didn't work for the live app either, but again worked locally.

```
backend: {
    loadPath: function (lng) {
      return `${AWS_CONFIG.aws_app_translations_path}/${lng}/translation.json`
    },
    crossDomain: true
  }
```

This is my entire `i18n` file

```
/*global AWS_CONFIG */
/*eslint no-undef: "error"*/
import i18n from "i18next";
import LanguageDetector from "i18next-browser-languagedetector";
import Backend from "i18next-http-backend";
import { initReactI18next } from "react-i18next";


const options = {
  order: ['navigator', 'localStorage'],
  caches: ['localStorage'],
  fallbackLng: "en-GB",
  debug: true,
  interpolation: {
    escapeValue: false // not needed for react as it escapes by default
  },
  backend: {
    loadPath: function (lng) {
      return `${AWS_CONFIG.aws_app_translations_path}/${lng}/translation.json`
    },
    crossDomain: true
  }
}

i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init(options);

export default i18n;
```

What could explain this odd behaviour? Am I missing configuration here?

**Comment by adrai** [comment]
Have you checked the i18next debug output for strange stuff?
If the urls is not constructed correctly with your settings there must be a problem before passing them to i18next...
Make sure your url is correct before passing to i18next.

If nothing helps: Can you create a reproducable example?

**Comment by hyprstack** [comment]
Yeah there is nothing odd in the debug output when it doesn't work apart from the fact it can't find the keys for that page. Apart from that the only other odd behaviour is the way it constructs the url as I mentioned above.

Well it would be hard to create a reproducible example.

**Comment by adrai** [comment]
maybe show some screenshots of the network tab? on localhost and when deployed?

**Comment by hyprstack** [comment]
These are the screenshot of the network tab on live when using `loadpath` as a function to dynamically build the url where the translations are stored. The blocked out bit of the url is not the base url of the target s3 bucket, but rather the base path of the app, which in itself is incorrect.

<img width="861" alt="Screenshot 2020-07-15 at 09 34 32" src="https://user-images.githubusercontent.com/5845311/87523383-c7e3de80-c67e-11ea-937a-cb8803f5d59e.png">
<img width="858" alt="Screenshot 2020-07-15 at 09 35 28" src="https://user-images.githubusercontent.com/5845311/87523389-c9150b80-c67e-11ea-9bc7-1d8f7293177b.png">

Also for some reason it is making two requests, one for 'en' and another for 'en-GB'. I would not expect it to make two api calls, but only one.

This is the network shot from the local application. As you can see it is making the request to the desired S3 endpoint and returning the correct translation file.

<img width="847" alt="Screenshot 2020-07-15 at 09 45 57" src="https://user-images.githubusercontent.com/5845311/87524712-6ae92800-c680-11ea-93c5-ac62f7ea5c20.png">

**Comment by adrai** [comment]
Is AWS_CONFIG.aws_app_translations_path} string with a slash?
That undefined in the url seems rather strange...

There are 2 requests because of the i18next load option. Maybe you need languageOnly.

Btw what is your console.log outputting?

**Comment by hyprstack** [comment]
AWS_CONFIG.aws_app_translations_path is some thing like `https://s3-region.amazonaws.com/my.bucket.translations`

Does having a / in the string make it do something?

As you can see form my config above I decided to log the constructed url and this is what is output: `undefined/en-GB/translation.json`.

Other than that, this is the output of from the debug option in the console.

<img width="861" alt="Screenshot 2020-07-15 at 10 44 31" src="https://user-images.githubusercontent.com/5845311/87530473-485b0d00-c688-11ea-800c-0c042a625ae5.png">
<img width="849" alt="Screenshot 2020-07-15 at 10 44 45" src="https://user-images.githubusercontent.com/5845311/87530488-4bee9400-c688-11ea-9650-627deb9defa9.png">

**Comment by adrai** [comment]
if this is the output... `undefined/en-GB/translation.json`
You need to check your `AWS_CONFIG.aws_app_translations_path` value... that value seems undefined

**Comment by hyprstack** [comment]
Strangely enough, AWS_CONFIG.aws_app_translations_path is returning as undefined, but only on live. This is odd as it is coming from the same config file used throughout the entire app, which works.

**Comment by adrai** [comment]
so... seems not related to this package... can this be close?

**Comment by hyprstack** [comment]
Yes.
Thanks for the help. I shouldn't have assumed that the config would work just because it was working for the rest of the app.

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
