### ISSUE TITLE
Add option to retry requests

### ISSUE THREAD

**Issue by erasmo-marin** [i18next/i18next-http-backend#22]
## 🚀 Feature Proposal

Add option to retry requests in case of error.

## Motivation

Currently I'm working on an app that has all translations inside the bundle. To optimize this and reduce bundle size, we are moving translations to json files. I have found that a lot of users can get network errors, and I have not been able to find any api to re-do requests if some fails because of a network error, also this plugin is not doing any retry. This is a big real world problem in production environment for apps that receive thousands of visits every day, so the proposal is to add configuration api to allow retries.

Sorry if this feature is already available, then we can change this issue description to update docs.

## Example

Proposal

```
{
  retry: {
      attempts: 5,
      interval: 500 /*in ms*/
  }
}
```

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L138 i18next core already does retry

**Comment by erasmo-marin** [comment]
It's not working for me, If I block requests, it does nothing

**Comment by adrai** [comment]
Is it a retriable status code?

https://github.com/i18next/i18next-http-backend/blob/master/lib/index.js#L65

**Comment by erasmo-marin** [comment]
> https://github.com/i18next/i18next-http-backend/blob/master/lib/index.js#L65

I get it, so the problem is that you expect to receive a status code. The problem is that network errors do not return status codes and fetch API will reject the promise. In such case, i18next is not retrying. That's the problem we are having. Network errors can be temporal, so I think i18next should retry if the fetch request is rejected anyways.

What do you think?

**Comment by adrai** [comment]
Would changing that line to:
`if (res && ((res.status >= 500 && res.status < 600) || !res.status)) return callback('failed loading ' + url, true /* retry */)`
work for you?

**Comment by adrai** [comment]
I'm going to create a new patch release, you can try with.

**Comment by adrai** [comment]
v1.0.18

**Comment by erasmo-marin** [comment]
I think that will work!

**Comment by erasmo-marin** [comment]
I confirm it works like a charm! awesome, thanks!

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏

**Comment by lenadss** [comment]
Hi guys,

Is there any possibility to configure that retry mechanism? For example to disable at all or to decrease retry attempts (if I'm not mistaken currently it is 5 by default https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L138)

**Comment by adrai** [comment]
It will not retry if your http status code is in this range: res.status >= 400 && res.status < 50

**Comment by markymc** [comment]
I would also like the ability to configure the retry count limit.

**Comment by adrai** [comment]
> I would also like the ability to configure the retry count limit.

This is done automatically in the i18next core...

**Comment by jamuhl** [comment]
Feel free to add a PR setting that inside an option: https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L138
