### ISSUE TITLE
Lack of support for file schema prevents use in cordova app

### ISSUE THREAD

**Issue by AgDude** [i18next/i18next-http-backend#23]
## 🐛 Bug Report

When used in a cordova app with a local translation file the url is something like `file:///android_asset/www/locale/es-US.json`  The fetch API does not support the file schema.

## To Reproduce

Load a locale json file from a `file://` url.

The following output is logged: `Fetch API cannot load file:///android_asset/www/locale/es-US.json. URL scheme "file" is not supported`

## Expected behavior

The json loads

## Your Environment

"Mozilla/5.0 (Linux; Android 7.1.1; Moto E (4) Plus Build/NDRS26.58-33-9-16; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/84.0.4147.125 Mobile Safari/537.36"

Within a cordova app (android webview)

**Comment by adrai** [comment]
This is an http adapter, not a file adapter...
Maybe this helps: https://github.com/i18next/i18next-fs-backend

**Comment by AgDude** [comment]
@adrai  Cordova is not node. The fs backend won't work in cordova. Cordova works using http, and all files are served with the `file://` scheme.  Perhaps a completely separate plugin is required, but this should work if it is allowed to fallback to XHR.

**Comment by jamuhl** [comment]
@AgDude might be time for a custom backend plugin: https://www.i18next.com/misc/creating-own-plugins

(you also can chain multiples: eg. HTTP and file:// -> https://github.com/i18next/i18next-chained-backend)

**Comment by adrai** [comment]
Sorry, never worked with Cordova...
This module uses the offered fetch api by the runtime and if not there, the XMLHttpRequest...
If this is not suitable for you, you may override the request option to pass an own request function => https://github.com/i18next/i18next-http-backend#backend-options

**Comment by AgDude** [comment]
Thanks for the pointer on requestOptions as a function. I can probably make that work.

**Comment by McGiverGim** [comment]
@AgDude did you fix this? I have the same problem.

**Comment by AgDude** [comment]
Here is what I ended up with. We had to copy request class from i18next to deal with some other issues around status code, which I think are not documented earlier in this issue.  Our initialization also ended up a bit ugly, because depending on your javascript framework within cordova (ionic v1 in this case), you can't let the application initialize until after the translation strings are loaded.

```
function requestWithXmlHttpRequest (options, url, payload, callback) {
  if (payload && typeof payload === 'object') {
    // if (!cache) payload._t = Date.now()
    // URL encoded form payload must be in querystring format
    payload = addQueryString('', payload).slice(1)
  }

  try {
    let x
    x = new XMLHttpRequest();
    x.open('GET', url, 1)
    if (!options.crossDomain) {
      x.setRequestHeader('X-Requested-With', 'XMLHttpRequest')
    }
    x.withCredentials = !!options.withCredentials
    if (payload) {
      x.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded')
    }
    if (x.overrideMimeType) {
      x.overrideMimeType('application/json')
    }
    let h = options.customHeaders
    h = typeof h === 'function' ? h() : h
    if (h) {
      for (var i in h) {
        x.setRequestHeader(i, h[i])
      }
    }
    x.onreadystatechange = () => {
      x.readyState > 3 && callback(x.status >= 400 ? x.statusText : null, { status: x.status || 200, data: x.responseText }) // in android webview loading a file is status status 0
    }
    x.send(payload)
  } catch (e) {
    console && console.log(e)
  }
}


i18next
.use(window.i18nextHttpBackend)
.init({
  backend: {
    loadPath: 'locale/{{lng}}.json',
    request: requestWithXmlHttpRequest
  },
  load: 'currentOnly',
  ns: ['translation'],
  defaultNS: 'translation',
  lng: 'en-US',
  fallbackLng: 'en-US',
  languages: [{{{LANGUAGES}}}, 'dev']  // replaced by our build task with currently available languages
})
.then((t) => {
    var packages = {{{PACKAGES}}};  // This loads the application, but we don't want to load let that load without first initializing the languages or we end up caching some of the wrong/undefined strings
    console.log('loading packages');

    packages.forEach(function(pkg, index) {
      var scriptTag = document.createElement('script');
      scriptTag.async = false;
      scriptTag.setAttribute('src', pkg);
      document.head.appendChild(scriptTag);
    });

  });
```

**Comment by McGiverGim** [comment]
Thanks for your help!!
