### ISSUE TITLE
translation fetched but cannot be loaded

### ISSUE THREAD

**Issue by AdrienLemaire** [i18next/i18next-http-backend#24]
## 🐛 Bug Report

json translation files appear to be fetched, but i18n cannot load the data.
It appears that the data is not correctly downloaded from Google cloud storage bucket, but no error is returned and the fetch appears to be successful. Not sure how to debug that one.
I noticed that my fetches have a `sec-fetch-dest: empty` request header, but according to the [MDN doc](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Dest), the header seems to be set automatically by the browser and it's unclear if some **requestOptions** could fix the issue.

## To Reproduce
Here's my config:

i18n.ts
```ts
import Backend from "i18next-chained-backend";
import HttpApi from "i18next-http-backend"; // fallback http load
import LanguageDetector from "i18next-browser-languagedetector";
import LocalStorageBackend from "i18next-localstorage-backend"; // primary use cache
import i18n from "i18next";
import { initReactI18next } from "react-i18next";

import environment from "./environment";

const { debug, localesPath } = environment;

const backendOptions = [
  {
    debug,
    // prefix for stored languages
    prefix: "i18next_res_",
    // expiration
    expirationTime: 7 * 24 * 60 * 60 * 1000,
    // Version applied to all languages, can be overriden using the option `versions`
    defaultVersion: "",
    // language versions
    versions: {},
    // can be either window.localStorage or window.sessionStorage. Default: window.localStorage
    store: window.localStorage,
    /* below options */
  },
  {
    loadPath: `${localesPath}{{lng}}/{{ns}}.json`, // xhr load path for my own fallback
    // allow cross domain requests
    crossDomain: false,
    requestOptions: {
      // used for fetch, can also be a function (payload) => ({ method: 'GET' })
      mode: "no-cors", // Same as webpack files, request header 'sec-fetch-mode: no-cors'
      credentials: "same-origin",
      cache: "default",
    },
  },
];

i18n
  // load translations from http
  .use(Backend)
  // detect user language
  .use(LanguageDetector)
  // pass i18n down to react-i18next
  .use(initReactI18next)
  .init({
    debug: true,
    backend: {
      backends: [
        LocalStorageBackend, // primary
        HttpApi, // fallback
      ],
      backendOptions,
    },
    ns: ["common", "translation", "glossary", "auth"], // NOTE: keep synced with i18nextWebpackPlugin options
    defaultNS: "common",
    supportedLngs: ["en", "ja"],
    fallbackLng: "ja",

    keySeparator: ".", // we use keys in form messages.welcome

    interpolation: {
      escapeValue: false, // react already safes from xss
    },
  });

if (process.env.NODE_ENV !== "production") {
  const { applyClientHMR } = require("i18next-hmr"); // eslint-disable-line
  applyClientHMR(i18n);
}

export default i18n;
```

SwitchLanguage.tsx
```tsx
import i18n from "i18next";
import React, { SyntheticEvent, useEffect, useRef, useState } from "react";
import { useTranslation } from "react-i18next";

const SwitchLanguage: React.FC = () => {
  const [lang, setLang] = useState("ja");
  const { t } = useTranslation();
  const isFirstRender = useRef(true);

  useEffect(() => {
    // Skip the effect on the first render
    if (isFirstRender.current) {
      isFirstRender.current = false;
    } else {
      i18n.changeLanguage(lang);
    }
  }, [lang]);

  const handleChange = ({ target }: SyntheticEvent): void =>
    setLang((target as HTMLSelectElement).value);

  return (
    <select onChange={handleChange} value={lang}>
      <option value="ja">{t("lang.ja")}</option>
      <option value="en">{t("lang.en")}</option>
    </select>
  );
};

export default SwitchLanguage;
```

Checking from the console Network tab, the files are fetched with status code 200
![](https://i.imgur.com/wUXZ50D.png)

i18next backend connector fails to load the data:
![](https://i.imgur.com/d0WYLrZ.png)

Keys are shown instead of translations in the page:
![](https://i.imgur.com/60x4Wcr.png)

The data can not be examined from the browser console:
![](https://i.imgur.com/1vTcPvY.png)

Here a screenshots of request headers sent:
![](https://i.imgur.com/HomcDSb.png)

Accessing the file directly works fine
![](https://i.imgur.com/mVxJBR7.png)

## Expected behavior

I should be able to see the json code from the browser console and i18n should load the data correctly.
Works in the dev environment with webpack devServer

![](https://i.imgur.com/FSrqgzM.png)
![](https://i.imgur.com/TVjqk3v.png)

## Your Environment

- *runtime version*: Any browser
- *i18next version*: i.e. 19.5.4
- *os*: Linux

**Comment by adrai** [comment]
Does it work without chained backend? So only with i18next-http-backend?

**Comment by AdrienLemaire** [comment]
@adrai sorry, this was due to misunderstanding how CORS works. For one, I had not configured CORS on my cloud bucket. And by copying your example with requestOptions, I triggered the preflighted CORS request, which kept failing. Removing all `requestOptions` and `customHeaders` from by backend options and leaving it to the client's browser to add the proper headers solved the issue.
