### ISSUE TITLE
Dynamic request customHeaders

### ISSUE THREAD

**Issue by Luc9802** [i18next/i18next-http-backend#28]
## 🚀 Feature Proposal

The request is to have customHeaders that can change over calls, in particular Authorization one.
Already implemented in i18next-xhr-backend but now it is deprecated, link to commit [here](https://github.com/i18next/i18next-xhr-backend/pull/321).

## Motivation

The necessity is basically the same reported i18next-xhr-backend [here](https://github.com/i18next/i18next-xhr-backend/issues/301#issuecomment-472040650).

## Example

Initialize i18next without any token as Authorization header, login to your app and need to set the retrieved token into i18next backend plugin, for example to add missing labels.

**Comment by adrai** [comment]
Can you try with 1.0.21 ?

**Comment by Luc9802** [comment]
Thank you for the super fast response and... also implementation!
Tested in 1.0.21 and it seems to work as expected.

Remember to edit documentation accordingly ;)

**Comment by adrai** [comment]
Nice!

If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
