### ISSUE TITLE
Issue when loading our common translation files

### ISSUE THREAD

**Issue by ryanmccormickspok** [i18next/i18next-http-backend#29]
Hello,

I am reaching out because we are using your library along with `i18next` and `react-i18next`. Recently there was a string check added to your codebase that stopped our common translation files from getting loaded.
https://github.com/i18next/i18next-http-backend/blob/ce9de751ba3263b9c4d78f44817596f4f35fd1d0/lib/index.js#L72

The way I am reading the code is if a response comes back that is not a string it will stop there and not attempt to process any additional languages or namespaces. Because of the way our environment is set up, we sometimes receive HTML responses when a file is not found or in the case of a 403. I was able to validate this issue locally by building and linking.

Is it possible for the string check to be removed or add some kind of escape hatch for unique scenarios like ours?

To solve for the issue in the meantime, I rolled back our package file to 1.0.15 but would love to be able to use your latest releases moving forward. Any help or guidance would be appreciated.

**Comment by adrai** [comment]
The check was introduced to guarantee the parse function interface.
Is there a particular reason why you are not responding with a string response?
As an alternative you could pass in your custom request function and pre-parse the data there:
![image](https://user-images.githubusercontent.com/1086194/94233296-f516fd80-ff07-11ea-839d-6ffa0b4f5fac.png)

**Comment by ryanmccormickspok** [comment]
I really appreciate your quick response!

I understand idea behind making sure an interface is robust and guaranteed. I think it is a good thing for this project that the issue presented itself as our stack is running in a distributed environment where sometimes we don't have as granular control over how a response gets returned, especially when the response code is part of the 4xx or 5xx groups.

Before adding the string check update, was there a breaking issue you were solving for? If not, you should consider rolling the code in question back to the previous state without the string check. Not just for the issue I found here but this could be breaking a lot of other stacks that are using your library.

**Comment by adrai** [comment]
Yes, there was an issue.

But honestly I don't get what the problem is... if there is a 4xx or 5xx this is an error, and the data is ignored anyway by i18next.

Can you please share some reproducable example? or exmplain better why this is important to you, in case of 4xx or 5xx?

**Comment by ryanmccormickspok** [comment]
Problem is in addition to multiple langauges (en, en-US) we have multiple namespaces (translation and common). The way the string check is written, the translation.json is loading but not the common.json from our common CDN. When trying to load files for languages: en, en-US and en-US fails, a non 200 is returned with and object response and the whole thing breaks. 

When I link your code locally and take out the string check everything works like it should and can confirm that I am getting object responses when en-US fails to load. End result is all out our common UI components no longer have translations when this happens.

**Comment by adrai** [comment]
I need a way to reproduce this... can you create an example?
btw: can you also please set debug to true and print the log here?
fyi: will be afk for the next hours

**Comment by adrai** [comment]
btw: you may want to override the parse function with something like this:


(str) => {
  try { return JSON.parse(str) }
  catch (e) { return {} }
}
