### ISSUE TITLE
Can not use this for Node 13.6.0

### ISSUE THREAD

**Issue by hoangthau** [i18next/i18next-http-backend#3]
When I use it with Node 13.6.0.

My code like this: 

`const httpApi = require('i18next-http-backend');
`

Here is error: 

`Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/thaunguyen/Documents/Projects/front-end/node_modules/i18next-http-backend/lib/index.js
require() of ES modules is not supported.
require() of /Users/thaunguyen/Documents/Projects/front-end/node_modules/i18next-http-backend/lib/index.js from /Users/thaunguyen/Documents/Projects/front-end/server/i18n.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/thaunguyen/Documents/Projects/front-end/node_modules/i18next-http-backend/package.json.`

But it works fine with node 12.x.x. Can I use `require` on Node 13.x.x?

**Comment by adrai** [comment]
How does your package.json look like?

**Comment by adrai** [comment]
Seems node v13.6 had some troubles with require...
just try another node version i.e v13.13.0

**Comment by hoangthau** [comment]
Thanks for quick reply. Because I have to use node 13.6.0 for docker image.  I will find an alternative solution.
