### ISSUE TITLE
Incorrect typings for RequestResponse

### ISSUE THREAD

**Issue by Basti237** [i18next/i18next-http-backend#31]
I'm using `i18next-http-backend` with typescript. I use the `request` function to load the message resources from a backend and receive the messages as JSON-Object. So if I want to call the `RequestCallback` I have to convert the JSON-Object to an JSON String via `JSON#stringify` to fullfill the typing of `RequestCallback` because the second param is of type `RequestResponse`. And there `data` should be of type `string`.

If I look to the code (https://github.com/i18next/i18next-http-backend/blob/master/lib/index.js#L72) I see that data doen't have to be of type string.

So is it possible to adjust the typing to something like this:

```
interface RequestResponse {
  status: number,
  data: string | Record<string, unknown>
}
```

Or why only a string is supported ?

**Comment by adrai** [comment]
Would you like to send a Pull Request to address this? Remember to add unit tests.
