### ISSUE TITLE
Does this library support python as backend ?

### ISSUE THREAD

**Issue by ahmedosama5200** [i18next/i18next-http-backend#32]
I know this is not a place for questions but I am really confused about what this library really does and I can't understand even after going through the documentation. I am not using nodejs in the backend. Do I still need it ?

**Comment by adrai** [comment]
You can use this library for example to connect from a browser (javascript) to a http api (this an be in any language, as long as it fulfills the api)

**Comment by ahmedosama5200** [comment]
Thank you for replying. What's the advantage of keeping translation files in my backend ? I could just leave them in the frontend and load them using webpack code splitting. Does that make sense ?

**Comment by adrai** [comment]
It's your choice...

You could update your translations without redeploying your frontend for example... like here: https://youtu.be/9NOzJhgmyQE

**Comment by ahmedosama5200** [comment]
Thank you so much. I get it now.
