### ISSUE TITLE
Parse option not working

### ISSUE THREAD

**Issue by McGiverGim** [i18next/i18next-http-backend#33]
## 🐛 Bug Report

I'm not sure if I understand exactly the `parse` option. I suppose is a way "modify" the json file with the translations before loading it.
I have a JSON like this:
```json
{
    "yes": {
        "message": "Si",
        "description": "General Yes message to be used across the application"
    },
    "no": {
        "message": "No",
        "description": "General No message to be used across the application"
    },
    ...
```
And I want to transform it like this:
```json
{
	"yes": "Si",
	"no": "No",
        ...
```

I have modified the `parse` function to accomplish that:
```javascript
parse(data) {
    // Remove the .message of each string
    const jsonData = JSON.parse(data);

    Object.entries(jsonData).forEach(([key, value]) => {
        jsonData[key] = value.message;
    });
    return JSON.stringify(jsonData);
}
```
The console log show the correct json, but when I do a `i18next.t('yes')`  it does not found the message.

I have tried the most simple, like this:
```javascript
parse(data) {
    return data;
}
```
But the `i18next.t('yes.message')` does not work neither to my surprise.

But if I remove the `parse` function totally, then it works perfectly, the `i18next.t('yes.message')` returns `Si`.

Is there something that I have not understood of this function?

## To Reproduce

Add an empty parse function to the options and test it:
```javascript
parse(data) {
    return data;
}
```

## Expected behavior

To find the keys.

## Your Environment

- *runtime version*: node v10
- *i18next version*: 19.5.1
- *os*: Windows
- *any other relevant information*

**Comment by adrai** [comment]
Remove the JSON.stringify call and just return the object

**Comment by adrai** [comment]
Btw: this only works if your http response is a string so no content-type: text

**Comment by adrai** [comment]
Why not changing directly the source json?

**Comment by McGiverGim** [comment]
Thanks!! Returning the JSON just works.

We can change it in a preprocess in our gulpfile when building the app too, but I wanted to test both options.

Thanks for your fast help!!! Closing this issue now ;)

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏

**Comment by McGiverGim** [comment]
Of course, and thanks from the Betaflight Configurator project!!! I have added this plugin here: https://github.com/betaflight/betaflight-configurator/pull/2230
