### ISSUE TITLE
Fetch won't return data

### ISSUE THREAD

**Issue by otaviobps** [i18next/i18next-http-backend#34]
For some strange reason, using the default fetch won't return any data from the S3 bucket where my translation files are. Here are my configs:

```
{
        lng: getLocales()[0].languageCode,
        fallbackLng: 'en',
        debug: false,
        interpolation: {escapeValue: false},
        keySeparator: false,
        nsSeparator: false,
        load: 'currentOnly',
        defaultNS: 'main',
        ns: 'main',
        backend: {
            crossDomain: true,
            loadPath:
                'https:/bucket.s3.eu-west-2.amazonaws.com/app/{{lng}}/{{ns}}.json',
        },
    }
```

The request returns a 200, but with no data:

![image](https://user-images.githubusercontent.com/28715087/99262906-469f8280-27fd-11eb-9d83-5ae45cf53ded.png)

![image](https://user-images.githubusercontent.com/28715087/99263003-659e1480-27fd-11eb-9e02-f119c7443e92.png)

This is a problem with fetch, I'm not sure why. Then I moved to axios:

```
{
        lng: getLocales()[0].languageCode,
        fallbackLng: 'en',
        debug: false,
        interpolation: {escapeValue: false},
        keySeparator: false,
        nsSeparator: false,
        load: 'currentOnly',
        defaultNS: 'main',
        ns: 'main',
        backend: {
            crossDomain: true,
            async loadPath(lng, ns) {
                const translations = await axios.get(
                    `https://bucket.s3.eu-west-2.amazonaws.com/app/${lng[0]}/${ns[0]}.json`,
                );
                return translations.data;
            },
        },
    }
```

This works fine, but it tries to make a strange request as well:

![image](https://user-images.githubusercontent.com/28715087/99263256-b9106280-27fd-11eb-8935-199212d131a2.png)

How should I configure the backend to use axios?

**Comment by adrai** [comment]
regarding fetch... i don't think there is a problem with fetch, but with your cors configuration...

regarding axios... you are configuring the loadPath function, this should return a string representing the path, not directly the data
if you want to use axios you may want to configure the request option

**Comment by adrai** [comment]
nevertheless a reproducable example would be nice

**Comment by otaviobps** [comment]
Hi @adrai, thanks for replying. It's definetely not a problem with cors, I've configured it in the S3, and axios can fetch the data just fine. I tried testing with `fetch` on a component and the same thing happened. Axios works, fetch doesn't.

> regarding axios... you are configuring the loadPath function, this should return a string representing the path, not directly the data

Can you elaborate this? I tried to return the data directly. If it's to return the path, how should I make the backend use axios instead of fetch?

Thanks!

**Comment by adrai** [comment]
you can define your own request functionality:
![image](https://user-images.githubusercontent.com/1086194/99573268-2aa30900-29d6-11eb-8ce6-725d05ee063a.png)

**Comment by otaviobps** [comment]
Thanks @adrai, it seems to be working now. Just to be sure the request is correctly:

```
request: async (options, url, payload, callback) => {
                try {
                    const translation = await axios.get(url);
                    callback({
                        status: 200,
                        data: JSON.stringify(translation.data),
                    });
                } catch (e) {
                    callback(e);
                }
            },
```
This should be the function, right?

**Comment by adrai** [comment]
I don't know axios... so if it works for you then ok. 👍

**Comment by otaviobps** [comment]
Thank you, closing it
