### ISSUE TITLE
options not merged ?

### ISSUE THREAD

**Issue by franck34** [i18next/i18next-http-backend#36]
Hi,

In a browser context, seem's that options are not taken.

```
        var boptions = {
            queryStringParams: { v: '1.2.3' },
        };

        var backend = new i18nextHttpBackend(boptions);

```

You can see in the network console that the query string is never passed.

After some investigation i found that.

Actual (not working, chrome browser):
```
      var options = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};
```

Expected (working)
```
      var options = arguments.length > 1 && arguments[0] !== undefined ? arguments[0] : {};
```

Cheers

**Comment by adrai** [comment]
There's a test here: https://github.com/i18next/i18next-http-backend/blob/master/test/request.spec.js#L21
and this is the relevant code: https://github.com/i18next/i18next-http-backend/blob/master/lib/request.js#L32
I can't reproduce your issue.
Can you provide a codesandbox exampe?

**Comment by franck34** [comment]
https://codesandbox.io/s/bold-ives-2rcyo?file=/src/index.js

You are supposed to see test.json?v=xxxxxxx in network console, but not.

**Comment by franck34** [comment]
I see your sample in React, which is working. Perhaps something related to pure js usage ?

**Comment by adrai** [comment]
You are passing the options in the wrong way.
Either: https://codesandbox.io/s/spring-violet-k5yfj
The options are passed as second argument when using the constructor function.

Or: https://codesandbox.io/s/romantic-microservice-m4vm5

**Comment by franck34** [comment]
Tssss ... i feel stupid a second time lol

Thanks a lot.

Closing !

**Comment by adrai** [comment]
Don't worry happens to me too ;-)

If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
