### ISSUE TITLE
invalid JSON file notification

### ISSUE THREAD

**Issue by franck34** [i18next/i18next-http-backend#37]
Hi again,

I lost 2 hours because of a missing coma in my json files (server side)

I suggest to add something (at least a message in the console) or something to handle bad json files ;)

Cheers

**Comment by adrai** [comment]
i18next has a debug: true option

**Comment by franck34** [comment]
the debug: true option does not notify about a problem with json files

**Comment by franck34** [comment]
I can PR if you want ;)

**Comment by adrai** [comment]
Can you show your console output when having debug: true?

**Comment by franck34** [comment]
I'm using the latest version of i18next and i don't have the message you just show me.

Below a non working case (my french language got a missing coma)

```
i18next::backendConnector: loaded namespace login for language en {messages: {…}}
i18next.min.js:1 i18next: languageChanged fr
```

Now, let's add the missing coma
```
i18next::backendConnector: loaded namespace login for language fr {messages: {…}}
i18next::backendConnector: loaded namespace login for language en {messages: {…}}
i18next.min.js:1 i18next: languageChanged fr
```

Nothing say about a parsing problem on my side.

**Comment by adrai** [comment]
Can you please create a codesandbox example?

**Comment by franck34** [comment]
Interesting, i'm reading your code, you already implement that (line 200). But it does not show in the console with debug:true in i18next options.

For codesandox, i need some times. My application is on my laptop, not on this internet. Or, we can make a quick meeting (gotomeeting) so you can have directly access to my computer. as you want.

**Comment by franck34** [comment]
Well, give me sometimes so i can publish my app on my public server

**Comment by franck34** [comment]
App published, bug reproduced, but i don't want to put informations here. Is there a way to speak with you in private ? irc, slack ... thank you

**Comment by adrai** [comment]
It would be nice to have a reproducable example, like: https://codesandbox.io/s/blissful-tu-siy6i?file=/src/i18n.js

**Comment by franck34** [comment]
Ha, i misunderstood regading codesandbox.

So, https://codesandbox.io/s/wizardly-tree-x1ghd

Missing coma in english file doesn't show a particular warning in the console.

**Comment by franck34** [comment]
Working on a minimal pure js case, please wait

**Comment by adrai** [comment]
I see this:
![image](https://user-images.githubusercontent.com/1086194/101939257-05747580-3be5-11eb-8b72-3faf8b1fe4b9.png)

**Comment by franck34** [comment]
Yep. Got it.

In the chrome console, i set a custom log level because was tired of warnings, before make my mistake (missing coma).

I forget it. With defaults log level, i can see the warning.

Sorry for losing time man. Closing this ticket. Working on the second one
