### ISSUE TITLE
Using from own lib

### ISSUE THREAD

**Issue by duPleX93** [i18next/i18next-http-backend#38]
## 🐛 Bug Report

I would like to use I18next from my own library but loadPath searching in main app (where I init-ed I18Next first time).
In my lib I would like to add a new namespace and some translation files. How can I trigger my lib dir?

## To Reproduce

My lib ts:
```js
ngOnInit(): void {
    i18next.init({
      ns: 'dialog',
      backend: {
        loadPath: '/assets/locales/{{ns}}-{{lng}}.json'
      }
    });
  }
```

## Expected behavior

```js
zone-evergreen.js:1068 GET http://localhost:4200/assets/locales/dialog-hu.json 404 (Not Found)
```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by adrai** [comment]
Sorry, I don't understand what you want to do...
Can you create an example and explain it with more details?
What is the actual issue?

**Comment by duPleX93** [comment]
Sorry! So let me explain my problem.

I working on a monorepo project, so I have main app, and other libs in my workspace. My using this libs like modules.
In the main app its easy to implement to use translation files:

app.module.ts
```js
export function appInit(i18next: ITranslationService) {
  return () => i18next.use(HttpApi).init({
    lng: localStorage.getItem('fullfield_app_language') || 'en',
    fallbackLng: ['en', 'hu'],
    debug: true,
    returnEmptyString: false,
    ns: [
      'app',
      'my-club'
    ],
    defaultNS: 'app',
    backend: {
      loadPath: '/assets/locales/{{ns}}-{{lng}}.json',
    }
  });
}

// tslint:disable-next-line:typedef
export function localeIdFactory(i18next: ITranslationService) {
  return i18next.language;
}

export const I18N_PROVIDERS = [
  {
    provide: APP_INITIALIZER,
    useFactory: appInit,
    deps: [I18NEXT_SERVICE],
    multi: true
  },
  {
    provide: LOCALE_ID,
    deps: [I18NEXT_SERVICE],
    useFactory: localeIdFactory
  }];
```

But in one of my lib I can't load source json, cause it try to find in main app's folder.

dialog.component.ts (lib)
```js
ngOnInit(): void {
    i18next.init({
      ns: 'dialog',
      backend: {
        loadPath: '/assets/locales/{{ns}}-{{lng}}.json'
      }
    });
  }
```

How can I set loadPath to search in my lib dir?

**Comment by adrai** [comment]
Sorry, I really don't understand.
Are you asking to reinitialize i18next? why?
Do you need a more dynamic loadPath? if so, just pass a function:
`loadPath: (lng, ns) => { return '/assets/locales/{{ns}}-{{lng}}.json'; }`

**Comment by duPleX93** [comment]
Separated in my libs, I like to load paths in the current lib dir, not from main app dir.

Or other solution: add more loadPath in the init function.
So in the main app init load multiple paths, example:
i18next.init({
      ns: ['ns1', 'ns2', 'ns3'],
      backend: {
        loadPath: '/assets/locales/{{ns}}-{{lng}}.json',
        loadPath: '../../dialog-lib/assets/locales/{{ns}}-{{lng}}.json
      }
    });

But how?
Are you understand me?

**Comment by adrai** [comment]
i18next is a singleton.
You may need to use createInstance: https://github.com/i18next/react-i18next/issues/1223#issuecomment-742831915

**Comment by duPleX93** [comment]
I see, okay.
Make it easier :)
I have to import translation files from different places (more loadPaths). Is it possible?

**Comment by adrai** [comment]
> I have to import translation files from different places (more loadPaths). Is it possible?

No, but maybe having a dynamic loadPath function helps?

`loadPath: (lng, ns) => { return '/assets/locales/{{ns}}-{{lng}}.json'; }`

**Comment by duPleX93** [comment]
I don't understand exactly how can I implement your code above.

**Comment by adrai** [comment]
> I don't understand exactly how and where can I implement your code above.

```js
i18next.init({
    ns: ['ns1', 'ns2', 'ns3'],
    backend: {
        loadPath: (lng, ns) => {
            // do you logic here, to change the path accordingly...
            return '/assets/locales/{{ns}}-{{lng}}.json';
        }
    }
});
```

**Comment by duPleX93** [comment]
yeah, it might be a good approach and a great solution for me, but now I get 404 for following:

backend: {
      loadPath: (lng, ns) => {
        let path;

        switch (ns) {
          case 'app':
            path = '/assets/locales/{{ns}}-{{lng}}.json';
            break;
          case 'my-club':
            path = '/assets/locales/{{ns}}-{{lng}}.json';
            break;
        }
        return path;
      }
    }

![image](https://user-images.githubusercontent.com/10195170/102221858-f5a9a980-3ee2-11eb-9e24-8273e1d8ea92.png)

**Comment by adrai** [comment]
sorry, missed to tell you, these are arrays:
![image](https://user-images.githubusercontent.com/1086194/102222200-681a8980-3ee3-11eb-93b3-9c4ff2e3d5ff.png)

```js
backend: {
    loadPath: (lngs, nss) => {
        let path;
        switch (nss[0]) {
            case 'app':
                path = '/assets/locales/{{nss[0]}}-{{lngs[0]}}.json';
                break;
            case 'my-club':
                path = '/assets/locales/{{nss[0]}}-{{lngs[0]}}.json';
                break;
        }
        return path;
    }
}
```

**Comment by duPleX93** [comment]
It's not working yet does not see the variables:

backend: {
      loadPath: (lngs, nss) => {
        let path;

        switch (nss[0]) {
          case 'app':
            path = '/assets/locales/{{nss[0]}}-{{lngs[0]}}.json';
            break;
          case 'my-club':
            path = '/assets/locales/{{nss[0]}}-{{lngs[0]}}.json';
            break;
          default:
            path = null;
        }
        return path;
      }
    }

![image](https://user-images.githubusercontent.com/10195170/102223404-f5121280-3ee4-11eb-86c0-9be514b645d2.png)

**Comment by adrai** [comment]
Can you console.log(path) and console.log(nss)?

**Comment by duPleX93** [comment]
sure:
![image](https://user-images.githubusercontent.com/10195170/102224504-55ee1a80-3ee6-11eb-9ad0-3221fb5fe741.png)

**Comment by adrai** [comment]
should be a template string now...
`/assets/locales/${nss[0]}-{lngs[0]}.json`;

**Comment by adrai** [comment]
btw: the path in your switch case seems not to differ... you probably need to adapt that

**Comment by duPleX93** [comment]
It's working almost :)))
Back to my original problem. I have to refer to lib.
![image](https://user-images.githubusercontent.com/10195170/102225886-03156280-3ee8-11eb-8d78-2bfb0d8435c3.png)

**Comment by adrai** [comment]
it depends where this files are hosted...
just return that path...
for example:
```js
`/../..fullfied-domain-lib/assets/locales/${nss[0]}-${lngs[0]}.json`;
```

i really don't know where these files are hosted... it's your app ;-)

btw: you should also be able to define a complete different domain, i.e. https://some-other-domain.com/assets/....

**Comment by duPleX93** [comment]
I18Next inited in fullfield-app/src/app/app.module.ts
'fullfield-app/src/app/assets/locales' is easy to refer
but the problem is 'fullfield-domain-lib/fullfield-myclub/src/lib/locales' 

![image](https://user-images.githubusercontent.com/10195170/102227125-7cfa1b80-3ee9-11eb-86ce-268b44b8d03b.png)

**Comment by adrai** [comment]
The question is where is this hosted on your server?

What's the url to access these files?

**Comment by duPleX93** [comment]
It exists only in localhost at this time.

**Comment by adrai** [comment]
ok, and which url?
http://localhost:4200/where/are/the/files

**Comment by duPleX93** [comment]
I really like to know :D
What is URL of node_modules dir?

**Comment by adrai** [comment]
Is someone in your team that will be responsible to deploy that app?
DevOps? Reliability-Engineer?

I suspect you are following the wrong path.

**Comment by duPleX93** [comment]
The answer is simple, because of library behaviors we can't do that. So every translation files will be in app/src/...
Thank you very much, and sorry about the waste your time!
