### ISSUE TITLE
Backend pulls "en" in addition to other languages

### ISSUE THREAD

**Issue by DanielLuu** [i18next/i18next-http-backend#39]
## 🐛 Bug Report

Backend pulls "en" in addition to other languages even when another fallbackLng is specified.

loadPath: '/api/translations?lang={{lng}}',

**Comment by adrai** [comment]
How does your i18next config look like?
https://www.i18next.com/overview/configuration-options
![image](https://user-images.githubusercontent.com/1086194/102277384-7fc83100-3f28-11eb-9e5b-d6feff7d19b9.png)
Can you create a reproducible example?

**Comment by DanielLuu** [comment]
@adrai thank you so much!
