### ISSUE TITLE
Serving json files from static folder in custom config webpack i.e not create-react-app

### ISSUE THREAD

**Issue by ALau2088** [i18next/i18next-http-backend#41]
Hi, I have similar question to https://github.com/i18next/i18next-http-backend/issues/1 but specifically pertaining to react app with   custom webpack configuration i.e not create-react-app. The public folder is located somewhere different than where it would be in a create-react-app. How do I set the i18n config to the location of the public folder? So far I tried 
![image](https://user-images.githubusercontent.com/37641224/105075662-e4524080-5a3e-11eb-9aac-7c882c564da8.png)
Thanks in advance!

**Comment by adrai** [comment]
I don't know where your files are served... 
Try to find the place where it's served by trying the url directly in the browser, like: `http://localhost:8080/public/locales/es/translation.json` and if that is a match, replace the language and the namespace like this: `loadPath: "http://localhost:8080/public/locales/{{lng}}/{{ns}}.json"`

**Comment by ALau2088** [comment]
Hi @adrai . I tried that and it still does not work.  
![image](https://user-images.githubusercontent.com/37641224/105079054-bb807a00-5a43-11eb-99e5-e47f81a9b945.png)
![image](https://user-images.githubusercontent.com/37641224/105079098-cc30f000-5a43-11eb-8358-410aac0a116d.png)
I get this error in the console. 
![image](https://user-images.githubusercontent.com/37641224/105079139-dce16600-5a43-11eb-82ca-02e171af38dd.png)

**Comment by adrai** [comment]
As you are on localhost and using https, I assume before the missingKey statement you get some sort of failed http request error.
Your browser probably has not included the self-signed ssl certificates

**Comment by ALau2088** [comment]
Hi @adrai . I was able to fix the issue. I realized my webpack config was not including the json files in the build. Once I fixed that, it worked. Thanks for your help!
