### ISSUE TITLE
Reload interval set to false not working

### ISSUE THREAD

**Issue by sofi-d** [i18next/i18next-http-backend#42]
## 🐛 Bug Report

Running on server side, I have an init configuration that, when reading an environment variable that it is "true" allows me to load translations from and endpoint, and when the envvar is false, I add them from a js object. In this case, I would like to avoid reloading as well.
Currently I am passing down that option but it is ignored, reload happens every hour. When setting debug: true, the i18next: initialized event shows that reloadInterval is indeed false.

## To Reproduce

Here's the portion of init config that enables this behavior, other parameters are not listed to simplify reading.
CONFIG.ENABLE_TRANSLATIONS is the env var that I mentioned, which is set to false,
so reloadInterval is false and request throws an error.

```js
 backend: {
reloadInterval: CONFIG.ENABLE_TRANSLATIONS && CONFIG.TRANSLATIONS_SERVER_RELOAD_INTERVAL,
    loadPath: (lngs, namespace) =>
      `${CONFIG.API_BASE_URL}${API_ROUTES.LOCALIZATION}/${lngs}_${namespace}`,
    request: async function(options, url, payload, callback) {
      try {
        if (!CONFIG.ENABLE_TRANSLATIONS)
          throw new Error('Backoffice translations disabled  - Loading static keys')

        //REQUEST TO BACKEND
        return callback(null, {
          status: result.status,
          data: result.data && result.data.translations
        })
      } catch (error) {
        return callback(
          {
            status: error.response && error.response.status,
            data: (error.response && error.response.data) || error.message
          },
          null
        )
      }
    }
  }

```

Here's is the portion where I load the js object in case of error or envvar being disabled:
```js
i18n
  .use(Backend)
  .use(i18nextMiddleware.LanguageDetector)
  .use(i18nCustomLogger)
  .init(serverOptions, i18nError => {

    if (i18nError) {
      logError('I18n Backend Connector error - Loading static keys', '', i18nError)
      i18n.addResourceBundle(LANGUAGE_TAGS.DEFAULT, NAMESPACES.COMMON, staticKeys)
    }
// some other code
```

## Expected behavior

I would like to avoid reloading when I set reloadInterval to false. 

## Your Environment

- *runtime version*: node v14
- *i18next version*: 19.5.1
- *os*: Mac

**Comment by adrai** [comment]
Can you check with v1.0.23 ?

**Comment by sofi-d** [comment]
That was fast! Now is working as expected. Thanks =D

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
