### ISSUE TITLE
Allow addPath to be a function

### ISSUE THREAD

**Issue by caal-15** [i18next/i18next-http-backend#45]
## 🚀 Feature Proposal

This would allow to provide a function for `addPath`, just as it is done from `loadPath`.

```javascript
const addPath = (lng, ns) => {
  // Decide what path to return according to ns/lng
}
```

## Motivation

This would basically account for a certain use case, using different paths based on __namespace__ and __language__ to post the missing resources, we have that ability when getting resources using `loadPath` as a function, but the same is not extended to the addPath property. 

## Example

We use the namespace to fetch data from two different backends, which we can perfectly do using `loadPath` as a function:

```javascript
const loadPath = (lngs, namespaces) => {
  if (namespaces[0] === "ns1") {
    return `/first/path/${lngs[0]}/${namespaces[0]}`
  }
  return `/second/path/${lngs[0]}/${namespaces[0]}`
}
``` 

We would also need to post missing resources to those different backends, something like:

```javascript
const addPath = (lng, namespace) => {
  if (namespace === "ns1") {
    return `/first/path/add/${lng}/${namespace}`
  }
  return `/second/path/add/${lng}/${namespace}`
}
```

**Comment by adrai** [comment]
Your PR was merged and is included in v1.1.0

If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
