### ISSUE TITLE
`create` function crashes if not provided with a callback

### ISSUE THREAD

**Issue by caal-15** [i18next/i18next-http-backend#47]
## 🐛 Bug Report

With the resolution of #45 a bug was introduced when posting missing resources, due to the fact that the `create` function may be called without a callback and that would cause the backend to crash.

## To Reproduce

1. Call `create` without a callback (`backend.create(languages, namespace, key, fallbackValue)`)

```js
import i18next from 'i18next'
const backend = new Http(
  {
    interpolator: i18next.services.interpolator
  }
)
// Produces "callback is not a function" error
backend.create('en', 'test', 'key', 'value')
```

## Expected behavior

The `create` function should work correctly without a callback.

## Your Environment

- *runtime version*: i.e. node v14.15.1, Firefox v85.0
- *i18next version*: i.e. 19.8.4
- *os*: Linux (WSL)

**Comment by adrai** [comment]
Are you sure?
the callback checked before calling it: if (callback) callback(dataArray, resArray)

**Comment by caal-15** [comment]
I actually didn't check the push you made, thanks for fixing mi slip-up! and sorry I didn't check before posting :P
