### ISSUE TITLE
Language interpolation in customHeader

### ISSUE THREAD

**Issue by ErikSattelmair** [i18next/i18next-http-backend#52]
## 🚀 Feature Proposal

Language interpolation in customHeader.

## Motivation

For a project, we’d like to fetch our translations from our backend. To indicate which translation for which backend should be requested, we’d like to use the “Accept-Language”-Header instead provide the information in the URL itself. 

## Example

We thought about something like:
```
...
customHeaders: {
    “Accept-Language”: “{{lng}}”
}
...
```
in the backend config. Is that possible already and I’m just incapable of making it work?

Thank you very much for your help!

**Comment by adrai** [comment]
No, this is currently not possible.

Normally there is a language-detector for i18next either on client side (https://github.com/i18next/i18next-browser-languageDetector) or on server side (https://github.com/i18next/i18next-http-middleware#language-detection). And the resulting language (decided by i18next) will be used to interpolate the fetching url.

**Comment by ErikSattelmair** [comment]
Hi @adrai, thank you very much for you quick reply and clarification.

Then we’ll go with the language in the URL.

Best regards
Erik
