### ISSUE TITLE
translation.json 404 error

### ISSUE THREAD

**Issue by benfiratkaya** [i18next/i18next-http-backend#53]
## 🐛 Bug Report

i18next-http backend, trying to get ns "translation" even though the default name is "common". And I get 404 error on console.
My code working well but I don't want get console error.

## My code:

```js
import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import backend from "i18next-http-backend";
import languageDetector from "i18next-browser-languagedetector";

i18n
  .use(initReactI18next) // passes i18n down to react-i18next
  .use(backend) // for /public/locales
  .use(languageDetector)
  .init({
    fallbackLng: "en",
    supportedLngs: ["en", "tr"],

    defaultNS: "common",

    keySeparator: false, // we do not use keys in form messages.welcome

    interpolation: {
      escapeValue: false, // react already safes from xss
    },
  });

export default i18n;

```

## My console log
request.js:60 GET https://tweet-maker-react.netlify.app/locales/en/translation.json 404

## My public folder
public
-- locales
---- en
------ common.json
---- tr
------ common.json

## Environment

- Node.js v12
- i18next version: 19.9.1
- Netlify

**Comment by adrai** [comment]
can you create a reproducible example?

**Comment by benfiratkaya** [comment]
> can you create a reproducible example?

https://github.com/benfiratkaya/tweet-maker-react

/src/utilities/i18n.js
/public/locales
My example usage: /src/components/Footer.js

**Comment by adrai** [comment]
The ns options also defaults to ['translation']:  https://www.i18next.com/overview/configuration-options
![image](https://user-images.githubusercontent.com/1086194/110203959-ff530580-7e70-11eb-99e1-c021f4869dbb.png)

So you need to change that too: ![image](https://user-images.githubusercontent.com/1086194/110203949-f7936100-7e70-11eb-9644-b6b20f2ae3c9.png)

**Comment by benfiratkaya** [comment]
> The ns options also defaults to ['translation']: https://www.i18next.com/overview/configuration-options
> ![image](https://user-images.githubusercontent.com/1086194/110203959-ff530580-7e70-11eb-99e1-c021f4869dbb.png)
> 
> So you need to change that too: ![image](https://user-images.githubusercontent.com/1086194/110203949-f7936100-7e70-11eb-9644-b6b20f2ae3c9.png)

Thank you! It's fixed.

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
