### ISSUE TITLE
i18next::backendConnector error Only absolute URLs are supported (SSR)

### ISSUE THREAD

**Issue by stanislav-sidorov-empeek** [i18next/i18next-http-backend#54]
## 🐛 Bug Report
Hi there, does anyone know what i'm doing wrong with backend config? seems to me this error is related to **i18next-http-backend**
Build fails with error **i18next::backendConnector: loading namespace translations for language en failed TypeError: Only absolute URLs are supported**

tried different backend libs with no success, this error appears only with i18next-http-backend

<img width="693" alt="Screenshot 2021-03-13 at 13 48 21" src="https://user-images.githubusercontent.com/79838991/111028969-cc75b800-8402-11eb-8401-8c6ec569b492.png">

## To Reproduce

```js
**i18n.js**
import i18n from 'i18next';
import Backend from 'i18next-http-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';

i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    backend: { loadPath: `/locales/{{lng}}/{{ns}}.json` },
    fallbackLng: 'en',

    // have a common namespace used around the full app
    ns: ['translations'],
    defaultNS: 'translations',

    debug: true,
    initImmediate: false,

    react: {
      wait: true
    }
  });

export default i18n;


**gatsby-ssr.js**

import React from 'react';
import { I18nextProvider } from 'react-i18next';

import { GlobalState } from './src/components/GlobalState/GlobalState';
import i18n from './src/utils/i18n';

import 'slick-carousel/slick/slick.css';

export const wrapRootElement = ({ element }) => (
  <I18nextProvider i18n={i18n}>{element}</I18nextProvider>
);

export const wrapPageElement = ({ element, props }) => (
  <GlobalState {...props}>{element}</GlobalState>
);

export const replaceRenderer = ({ bodyComponent, replaceBodyHTMLString }) => {
  i18n.loadNamespaces(['translations'], () => {
    replaceBodyHTMLString(bodyComponent);
  });
};


**gatsby-node.js**

exports.onPostBuild = () => {
  fs.copySync(`./src/locales`, `./public/locales`);
};

```

## Expected behavior

Build project without errors

## Your Environment

- *runtime version*: i.e. node v14.16.0, gatsby v2.24.91, ssr
- *i18next version*: 19.8.3
- *os*: Mac M1 chip, Big Sur 11.2.3

**Comment by adrai** [comment]
On server side (SSR) there is no browser having loaded your app... so the url: "/locales/{{lng}}/{{ns}}.json" is invalid... relative urls work only in browser environment.

This is why you should configure an absolute url....
