### ISSUE TITLE
Cannot combine local resources with backend resources

### ISSUE THREAD

**Issue by EmanuelBenHamo** [i18next/i18next-http-backend#55]
Hello,
I am trying to config my i18n to have local static json file: "backupMessages.json",
and also to fetch other messages file from CDN, by using i18next-http-backend.

I came to this configuration but it only loads the local static file "backupMessages.json",
without the files from the CDN:

![Screen Shot 2021-03-14 at 10 58 55](https://user-images.githubusercontent.com/27367048/111062861-49149f00-84b4-11eb-8f4c-9911d1b7597d.png)
 

couldn't find a way to make it work.

any help?
thanks :)

**Comment by adrai** [comment]
the backup backend needs to be at the second position.
Only if the first backend is not able to return the requested namespaces, it will fallback to the second backend

**Comment by EmanuelBenHamo** [comment]
@adrai I didn't understand your answer.
what should be changed in this config?

I am trying to get the backup file not from the CDN, but from another folder in my project (it is local static file).
I don't want to fetch the backup file from CDN, it has to be stored inside the app.

Is it possible to use backend to load local files, from another directory in the project?

**Comment by adrai** [comment]
if it's a react app, you have no access to the filesystem during runtime...
it would be possible to habe 2 different http-backends configured in a chained-backend, but I don't think this is what you are looking for

**Comment by EmanuelBenHamo** [comment]
all I want is to use backupMessages as fallback namespace in case loading the other namespaces from CDN will fail.
It it possible? how? still couldn't understand how to get it.

![Screen Shot 2021-03-14 at 11 39 01](https://user-images.githubusercontent.com/27367048/111063919-e32b1600-84b9-11eb-9c4e-ed0ab8c379a3.png)

**Comment by adrai** [comment]
You need to create your own backend and then chain it...
https://github.com/i18next/i18next-http-backend/blob/master/example/fallback/app.js

**Comment by EmanuelBenHamo** [comment]
@adrai Thanks for your help!
It solved my problem.

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
