### ISSUE TITLE
i18next do not complain when wrong `loadPath` is given

### ISSUE THREAD

**Issue by fxmarty** [i18next/i18next-http-backend#56]
## 🐛 Bug Report

`loadPath` seem not to be taken into account, and whether the path is valid or not the behavior is the same.

## To Reproduce

Run:

```js
const i18next = require('i18next')
const backend = require('i18next-fs-backend')

const options = {
    lng: 'en',
    fallbackLng: 'en',
    loadPath: '/path/is/wrong/translation.json',
}

i18next.use(backend).init(options)

// sleep time expects milliseconds
function sleep (time : number) {
    return new Promise((resolve) => setTimeout(resolve, time));
}

sleep(300).then(() => {
    console.log(i18next.languages)
    console.log(i18next.language)
    console.log(i18next.dir())
    console.log(i18next.exists('mykey.mymessage'))
});
```

The code executes well and returns exit code 0, output:

```
[ 'en' ]
en
ltr
false
```

Additionally, setting `loadPath` to the real path, e.g. `locales/en/translation.json`, still compiles well but the output is the same, even if my key `mykey.mymessage` does exist in my `translation.json` file:

```
{
  "mykey": {
    "mymessage": "hehe",
    "description": "haha"
  }
}
```

Then, this is very hard to debug because you don't know whether the problem is that your json file is not loaded, of if it is something else.

## Expected behavior

I would expect having an error because the path I give is wrong.

## Your Environment

- *runtime version*: node 14.15.5
- i18next-fs-backend@1.1.0
- i18next@19.9.2
- *os*: Linux

**Comment by fxmarty** [comment]
This should have been posted in https://github.com/i18next/i18next-fs-backend , I close sorry.

**Comment by adrai** [comment]
set debug to true and check the console output
