### ISSUE TITLE
New types breaks i18next-chained-backend compatibility

### ISSUE THREAD

**Issue by mxsxs2** [i18next/i18next-http-backend#58]
## 💥 Regression Report

The plugin overrides the backend type for i18next. This breaks existing code where developers use [i18next-chained-backend](https://github.com/i18next/i18next-chained-backend)

## Last working version

Worked up to version: 1.1.1

Stopped working in version: 1.2.0

## To Reproduce

Follow the guide at https://github.com/i18next/i18next-chained-backend

## Expected behavior

To work as before

## Your Environment

- *runtime version*: node v14.15.1
- *i18next version*: 20.0.0
- *os*: Windows and Linux (Alpine)

**Comment by adrai** [comment]
//cc @pedrodurek

**Comment by pedrodurek** [comment]
Hey @mxsxs2, can you provide an example?

**Comment by pedrodurek** [comment]
Ohh never mind, I just got what's happening, I'll see what I can do

**Comment by mxsxs2** [comment]
https://github.com/i18next/i18next-browser-languageDetector/pull/235 Will more than likely cause the same issue.

**Comment by pedrodurek** [comment]
Hey @adrai, we have to options:
1 - Implement the augmentation for the `i18next-chained-backend` plugin, but users would have to import `i18next-chained-backend` first.

![24-08-8jlp2-ijr0n](https://user-images.githubusercontent.com/12190482/112413080-959a7e80-8ced-11eb-967d-61523c255343.gif)

2 - Remove the augmentation from all **backend** plugins, and it's up to users to manually implement the augmentation.
3 - Alternatively, we can infer based on Backend passed to the `init` function, but that I'd cause major breaking changes.

Which one should we choose?

**Comment by adrai** [comment]
I have no clue... (I'm not a TypeScript user)
Maybe 1) or if not that much of a major break 3) 🤷‍♂️

**Comment by mxsxs2** [comment]
I think option 1 is good enough. If it is in the documentation then most people would understand it.

Option 3 would be good too but I am not sure if it is worth it to introduce a single braking change just for this. Maybe if there are more in the near future?

**Comment by yadigarbz** [comment]
> Hey @adrai, we have some options: 1 - Implement the augmentation for the `i18next-chained-backend` plugin, but users would have to import `i18next-chained-backend` first.
> 
> ![24-08-8jlp2-ijr0n](https://user-images.githubusercontent.com/12190482/112413080-959a7e80-8ced-11eb-967d-61523c255343.gif) [ ![24-08-8jlp2-ijr0n](https://user-images.githubusercontent.com/12190482/112413080-959a7e80-8ced-11eb-967d-61523c255343.gif) ](https://user-images.githubusercontent.com/12190482/112413080-959a7e80-8ced-11eb-967d-61523c255343.gif) [ ](https://user-images.githubusercontent.com/12190482/112413080-959a7e80-8ced-11eb-967d-61523c255343.gif)
> 
> 2 - Remove the augmentation from all **backend** plugins, and it's up to users to manually implement the augmentation. 3 - Alternatively, we can infer based on Backend passed to the `init` function, but that I'd cause major breaking changes.
> 
> Which one should we choose?

Can't believe this is the solution 😄
