### ISSUE TITLE
BackendOptions TypeScript interface missing reloadInterval

### ISSUE THREAD

**Issue by TrueWill** [i18next/i18next-http-backend#59]
## 🐛 Bug Report

`BackendOptions` TypeScript interface is missing `reloadInterval` (at a minimum).

https://github.com/i18next/i18next-http-backend/blob/master/index.d.ts#L7

## To Reproduce

```ts
const httpApiOptions: BackendOptions = {
  loadPath: '/locales/{{lng}}/{{ns}}.json',
  allowMultiLoading: false,
  crossDomain: false,
  reloadInterval: false,  // flagged by TypeScript
};
```

## Expected behavior

No TypeScript errors.

## Your Environment

- *runtime version*: TypeScript 4.2.3 in VSCode
- *i18next version*: 20.0.0
- *os*: Mac

**Comment by adrai** [comment]
@pedrodurek if you're already in progress of creating a PR for the other issue....
