### ISSUE TITLE
If I set the language is 'ko-KR', there will have two request 'ko' and 'ko-KR'

### ISSUE THREAD

**Issue by Rem486** [i18next/i18next-http-backend#61]
## To Reproduce

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
import i18n from 'i18next';
import Backend from 'i18next-http-backend';

i18n
  .use(Backend)
  .init({
    fallbackLng: 'ko-KR',
    preload: ['ko-KR'],
    backend: {
      loadPath: `http://localhost/api/translation-resource/{{lng}}`,
    },
    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
    },
  });
```
![image](https://user-images.githubusercontent.com/22462424/113391894-37495c00-93cf-11eb-8a8a-e42f0db9ae67.png)

## Expected behavior

only one request, or Is this normal ?

## Your Environment

- *runtime version*: i.e. chrome
- *i18next version*: i.e. 20.1.0
- *os*: Windows
- *any other relevant information*

**Comment by adrai** [comment]
Yes, this is expected: https://www.i18next.com/overview/configuration-options#languages-namespaces-resources
default load option is 'all'
![image](https://user-images.githubusercontent.com/1086194/113392060-d0a74c80-9394-11eb-88ba-be18e67bc61f.png)
