### ISSUE TITLE
Build fails with Vite and other rollup-based bundlers

### ISSUE THREAD

**Issue by diracs-delta** [i18next/i18next-http-backend#66]
## 🐛 Bug Report

Vite is a blazingly fast bundler and is being increasingly used amongst devs. I've recently gotten the product team at our company to use it more because webpack-dev-server can get extremely slow for large projects.

In production mode, Vite uses rollup internally to bundle code. The problem is, it seems that this library specifically is causing builds to fail with runtime errors on initial load.

To save you some time, I've already done a little bit of research and figured out the root of this problem. `node-fetch` is somehow being bundled into the browser in rollup. Thus the runtime errors are from trying to access non-existent node libs in the browser.

## To Reproduce

Pull from this test repo: https://github.com/diracs-delta/i18next-http-backend-rollup-demo

And then run

```
yarn
yarn vite build && yarn vite preview
```

and navigate to `localhost:5000`.

## Expected behavior

`i18next` plugins should be compatible with the latest bundlers and not sometimes import `node-fetch` on accident.

## Your Environment

- *runtime version*: node 15, any
- *i18next version*: see package.json
- *os*: Mac

**Comment by adrai** [comment]
This works fine in normal rollup setups... must be something special for vite build... sorry, I don't know vite...
Maybe this condition needs to be extended: https://github.com/i18next/i18next-http-backend/blob/master/lib/getFetch.cjs#L10

Would be nice if you could help in finding a solution.

**Comment by diracs-delta** [comment]
Dang. I was hoping that wasn't the case. Thank you for testing it on rollup setups. I'll see if I can find something.

**Comment by diracs-delta** [comment]
Note: I'm pretty unfamiliar with the quirks of CJS v.s. ESM, so bear with me if my vocabulary is a bit off.

The problem seems to be that in the compiled node module, the `esm/getFetch` gets compiled to a CJS file that uses a `require` statement, while Vite expects a ESM script that uses `import` statements. Changing the line

```
  var f = fetchApi || require('node-fetch')
```

to 

```
  var f = fetchApi || await import('node-fetch')
```

fixed the problem locally. Maybe we ought to tweak to build process to only generate ESM under `esm/`?

**Comment by adrai** [comment]
no, the only way to fix this by keeping the compatibility with node, deno, etc... is to change the if condition

**Comment by diracs-delta** [comment]
I moved the conditional within the if statement to a console log, which returned `false`. VIte might not be optimized enough to detect that, and is still trying to bundle `node-fetch`. Nevertheless, you are right. I truthfully don't know enough about CJS to understand what's actually going on here.

I'll reach out to Vite and link them this issue, but it might be worth considering using `cross-fetch` instead of trying to re-invent the wheel here. `cross-fetch` seems to work just fine on Vite, so if it isn't too much of a change, perhaps `i18next-http-backend` could switch to using `cross-fetch`?

**Comment by diracs-delta** [comment]
Wait, Evan You actually figured this out a few months ago! Check this out:

https://github.com/vitejs/vite/issues/2045

**Comment by diracs-delta** [comment]
@adrai It's fixed! Thank you so much! We can use `i18next` in our production builds now. I'll let the Vite community know that this update will fix their builds. 👍
