### ISSUE TITLE
Typescript definition is incorrect and resulting in a compilation failure

### ISSUE THREAD

**Issue by bert-bae** [i18next/i18next-http-backend#69]
## 🐛 Bug Report

Running `tsc` on the 1.2.5 and 1.2.6 versions to compile typescript results in the following error:

```
Class 'I18NextHttpBackend' incorrectly implements interface 'BackendModule<BackendOptions>'.
  Property 'create' is optional in type 'I18NextHttpBackend' but required in type 'BackendModule<BackendOptions>'.
```

There is no compilation issue for versions 1.0.x 

## Expected behavior

Typescript is able to compile.

## Your Environment

- Node 12.21.2
- i18next 19.4.4
- i18next-http-backend 1.2.6, 1.2.5 (haven't tested anything beyond that)

**Comment by adrai** [comment]
Does this also happen with the newest i18next version?

**Comment by adrai** [comment]
//cc: @pedrodurek

**Comment by pedrodurek** [comment]
That's odd, the property is optional in both dependencies, could you provide an example in Codesandbox or similar?

**Comment by bert-bae** [comment]
It looks like updating i18next to the latest works and has the correct type definitions in for in i18next `BackendModule` for it to compile correctly with i18next-http-backend.

Fix:
- Upgrade i18next to 20.x.x
