### ISSUE TITLE
Backend loadPath problem

### ISSUE THREAD

**Issue by mrrobotisback** [i18next/i18next-http-backend#7]
Goodmorning, 

i have a little problem when i try to load translation from my api.
Code:

```
import i18n from 'i18next'
import XHR  from 'i18next-http-backend';
import { initReactI18next } from 'react-i18next'
i18n.use(XHR)
    .use(initReactI18next)
    .init({
        backend: {
            loadPath         : 'urlexample/{{lng}}/{{ns}}/',
            allowMultiLoading: false,
            crossDomain      : false
        },
          lng: locale.split("-")[0],
          ns: locale.split("-")[1],
          defaultNS: locale.split("-")[1],
          react: {
              useSuspense: false
          },
        fallbackLng: false,
        debug: true,
        react: {
            wait: true
        }
    }, (error, t) => {
        if(error)
            console.error(error);
    });
```
Backend i18next log is this: 

![Backendconn](https://user-images.githubusercontent.com/23551496/80466736-3bf2ce00-893d-11ea-88fe-202226ae556e.png)

And the translation doesn't work.

what is my problem ?

Thanks in advance.

P.S.

When i use static hardcoded json like this work well:
```
import i18n from 'i18next'
import Backend from 'i18next-http-backend';
import LanguageDetector from 'i18next-browser-languagedetector'

import itit from './translations/it-it.json'

i18n
                    .use(Backend)
                    .use(LanguageDetector)
                    .use(initReactI18next)
                    .init({
                        lng: locale.split("-")[0],
                        react: {
                             useSuspense: false
                        }
                        fallbackLng: 'en',
                        debug: true,
                        resources: { en, itit, eses, ruru, roro, vivn, envn, zaza, enza, frfr, huhu, plpl, uaua, enid, idid, usus, enus, nlnl, ensg, elgr, frma },
                        interpolation: {
                            escapeValue: false,
                        },
                    })
            },
            (error) => {
                console.log(error, "i18n error loading");
            });

```
![Good](https://user-images.githubusercontent.com/23551496/80467705-8163cb00-893e-11ea-96ad-d11a228a4126.png)

**Comment by adrai** [comment]
Can you provide a codesandbox example or similar?
How does the request to your loadPath look like?
Can you also show me more of the i18next debugging logs?

**Comment by mrrobotisback** [comment]
Request loadpath response: 

```
"{\"menu\":{\"show more products\":\"show more products\",\"all-model-of\":\"Tutti i modelli di\",\"most-wanted\":\"I pi\\u00f9 ricercati\",\"technologies\":\"Tecnologie\",\"products\":\"Prodotti\",\"related-links\":\"LINK CORRELATI\",\"was-this-content-useful\":\"Questo contenuto \\u00e8 stato utile?\",\"yes\":\"Si\",\"no\":\"No\",\"your-address\":\"IL TUO INDIRIZZO\",\"your-appliance\":\"IL TUO APPARECCHIO\"}}"
```

**Comment by adrai** [comment]
ok, so probably, you are not serving json => content-type is not application/json ?

**Comment by mrrobotisback** [comment]
![backlogs](https://user-images.githubusercontent.com/23551496/80468531-90974880-893f-11ea-9d0c-90353c2474cb.png)

![Translatr](https://user-images.githubusercontent.com/23551496/80468567-9ee56480-893f-11ea-8dec-9315be3f8ff8.png)

**Comment by mrrobotisback** [comment]
> content-type is not application/json ?

do You mean that I have to set content type: application/json in the backend bee ?

**Comment by adrai** [comment]
I just tested with a stringified json and content-type test... this works...
so must be something else..
Can you create a reproducable example?

**Comment by adrai** [comment]
ahhh wait... is menu your namespace?
Then you should not add this to the json file...


instead of: `"{\"menu\":{\"show more products\":\"show more products\",\"all-model-of\":\"Tutti i modelli di\",\"most-wanted\":\"I pi\\u00f9 ricercati\",\"technologies\":\"Tecnologie\",\"products\":\"Prodotti\",\"related-links\":\"LINK CORRELATI\",\"was-this-content-useful\":\"Questo contenuto \\u00e8 stato utile?\",\"yes\":\"Si\",\"no\":\"No\",\"your-address\":\"IL TUO INDIRIZZO\",\"your-appliance\":\"IL TUO APPARECCHIO\"}}"
`

you should have this: `"{\"show more products\":\"show more products\",\"all-model-of\":\"Tutti i modelli di\",\"most-wanted\":\"I pi\\u00f9 ricercati\",\"technologies\":\"Tecnologie\",\"products\":\"Prodotti\",\"related-links\":\"LINK CORRELATI\",\"was-this-content-useful\":\"Questo contenuto \\u00e8 stato utile?\",\"yes\":\"Si\",\"no\":\"No\",\"your-address\":\"IL TUO INDIRIZZO\",\"your-appliance\":\"IL TUO APPARECCHIO\"}"
`

**Comment by mrrobotisback** [comment]
```
import i18n from 'i18next'
import XHR  from 'i18next-http-backend';
import { initReactI18next } from 'react-i18next'
i18n.use(XHR)
    .use(initReactI18next)
    .init({
        backend: {
            loadPath         : 'urlexample/{{lng}}/{{ns}}/',
            allowMultiLoading: false,
            crossDomain      : false
        },
          lng: 'it',
          ns: 'it',
          defaultNS: 'it',
          react: {
              useSuspense: false
          },
        fallbackLng: false,
        debug: true,
        react: {
            wait: true
        }
    }, (error, t) => {
        if(error)
            console.error(error);
    });
```
And the json return like this: 
```
{
"menu": {
    "all-model-of": "Tutti i modelli di ",
    "most-wanted": "I più ricercati ",
    "technologies": "Tecnologie"
   }
}
```

**Comment by mrrobotisback** [comment]
The api take 2 parames for now:

language and country, because in a country it is possible that we have 2 language. 
example:
italy:
it-it
en-it

**Comment by mrrobotisback** [comment]
Another point: 

if i change api for take all array of namespace. 

have i need to change the use of translation ? 

Now we use i 18next liek this:

**Comment by adrai** [comment]
> And the json return like this:
> 
> ```
> {
> "menu": {
>     "all-model-of": "Tutti i modelli di ",
>     "most-wanted": "I più ricercati ",
>     "technologies": "Tecnologie"
>    }
> }
> ```

loadPath expects to return a the json of the namespace so the file should contain this:

```json
{
     "all-model-of": "Tutti i modelli di ",
     "most-wanted": "I più ricercati ",
     "technologies": "Tecnologie"
}
```

**Comment by adrai** [comment]
> The api take 2 parames for now:
> 
> language and country, because in a country it is possible that we have 2 language.
> example:
> italy:
> it-it
> en-it

it-it is a fully specified regional language code (lng+country)

**Comment by adrai** [comment]
> if i change api for take all array of namespace.

Do you mean multiloading?
![image](https://user-images.githubusercontent.com/1086194/80473183-10281600-8946-11ea-9247-e4e0425173ed.png)

**Comment by mrrobotisback** [comment]
> > if i change api for take all array of namespace.
> 
> Do you mean multiloading?
> ![image](https://user-images.githubusercontent.com/1086194/80473183-10281600-8946-11ea-9247-e4e0425173ed.png)

I mean if i change api for take:

import i18n from 'i18next'
import XHR  from 'i18next-http-backend';
import { initReactI18next } from 'react-i18next'
i18n.use(XHR)
    .use(initReactI18next)
    .init({
        backend: {
            loadPath         : 'urlexample/{{lng}}/{{ns}}/',
            allowMultiLoading: false,
            crossDomain      : false
        },
          lng: 'it',
          ns: ['menu','search', ecc],
          defaultNS: false,
          react: {
              useSuspense: false
          },
        fallbackLng: false,
        debug: true,
        react: {
            wait: true
        }
    }, (error, t) => {
        if(error)
            console.error(error);
    });

Can i keep using t like this: 
t('menu:all-model-of')

**Comment by adrai** [comment]
yes

**Comment by mrrobotisback** [comment]
Ok thanks a lot. I try If i have other problem, i write under this post.

**Comment by adrai** [comment]
So can this issue be closed for now?

**Comment by mrrobotisback** [comment]
Yes thanks

**Comment by mrrobotisback** [comment]
here again. 
Another problem.
![SecondPorblem](https://user-images.githubusercontent.com/23551496/80478968-97798780-894e-11ea-945e-4fdab29217bb.png)

I fix the api and now take name space but now is second level problem.
Key:value problem

**Comment by adrai** [comment]
How does the response look like?
And your current settings?

**Comment by mrrobotisback** [comment]
Current settings: 
```
i18n.use(XHR)
    .use(initReactI18next)
    .init({
        backend: {
            loadPath         : 'url/{{lng}}/{{ns}}/',
            allowMultiLoading: false,
            crossDomain      : false
        },
        fallbackLng: false,
        debug: true,
        ns: ['base', 'home', 'breadcrumb','menu', 'form', 'product','search','media','acc','blog','seo','product-finder'],
        defaultNS: false,
        react: {
            wait: true
        }
    }, (error, t) => {
        if(error)
            console.error(error);
    });
```

Example partial response for menu:

```
"{\"show more products\":\"show more products\",\"all-model-of\":\"Tutti i modelli di\"}"
```

**Comment by mrrobotisback** [comment]
seems to be missing a json.parse before inject response of api into namespace

**Comment by adrai** [comment]
I have no idea how this can happen...
Can you try to make an example like here: https://github.com/i18next/i18next-http-backend/tree/master/example/node

**Comment by adrai** [comment]
If this is the resonse of the request this should work: `"{\"show more products\":\"show more products\",\"all-model-of\":\"Tutti i modelli di\"}"`

Can you send a screenshot of the network call incl. headers etc..?

**Comment by mrrobotisback** [comment]
If i remove json_encode before send response for backend api: 

![partialRight](https://user-images.githubusercontent.com/23551496/80480103-5bdfbd00-8950-11ea-8cf6-71a104bd839b.png)

but miss key of translation

**Comment by adrai** [comment]
Seems like you send strange data...
Can you please post the screenshot of the network call:
something like this:
![image](https://user-images.githubusercontent.com/1086194/80480321-b6791900-8950-11ea-9b76-433264659c8a.png)
and this:
![image](https://user-images.githubusercontent.com/1086194/80480340-c133ae00-8950-11ea-90b8-96d507d3547f.png)

**Comment by mrrobotisback** [comment]
![image](https://user-images.githubusercontent.com/23551496/80480785-8e3dea00-8951-11ea-96a0-a6b6788776fe.png)

**Comment by mrrobotisback** [comment]
![image](https://user-images.githubusercontent.com/23551496/80480818-9dbd3300-8951-11ea-9a34-cf2de20c161f.png)

**Comment by adrai** [comment]
your content-type is application/json but you send a stringified json

**Comment by adrai** [comment]
It's like you would json_encode 2x

**Comment by adrai** [comment]
proof:

```js
var ret = JSON.parse('"{\\"show more products\\":\\"show more products\\",\\"all-model-of\\":\\"Tutti i modelli di\\"}"')
console.log(ret) // still a string => {"show more products":"show more products","all-model-of":"Tutti i modelli di"}
if (typeof ret === 'string' && ret[0] === '{' && ret[ret.length - 1] === '}') {
  ret = JSON.parse(ret)
}
console.log(ret) // now it's an object
// {
//   'show more products': 'show more products',
//   'all-model-of': 'Tutti i modelli di'
// }
```

**Comment by adrai** [comment]
could you fix it?

**Comment by mrrobotisback** [comment]
Now this is the situation doesn't work.
![image](https://user-images.githubusercontent.com/23551496/80573652-a0c32c80-8a00-11ea-894d-b3703cbcbc5a.png)
I think the problem is that create a 0 cell after namespace...

**Comment by adrai** [comment]
Please post again the screenshot of the http response

**Comment by mrrobotisback** [comment]
I have solved for json. The problem is response from backend. Thanks for help.

But i have a question.

```
i18n.use(XHR)
    .use(initReactI18next)
    .init({
        backend: {
            loadPath         : url/{{lng}}/{{country}}/{{ns}}/',
            allowMultiLoading: false,
            crossDomain      : false
        },
        fallbackLng: false,
        debug: true,
       country: 'it',
       lng: 'it'
        ns: ['base', 'home', 'breadcrumb','menu', 'form', 'product','search','media','acc','blog','seo','product-finder'],
        defaultNS: false,
        react: {
            wait: true
        }
    }, (error, t) => {
        if(error)
            console.error(error);
    });

export default i18n
```
is there a way to use lng and country ? beacuse i have a specific translation for specific country.
Example:
en-it 
is different from 
en-gb

is there a way to achive this ?

thanks in advance.

**Comment by mrrobotisback** [comment]
Now is all ok thanks a lot.
![image](https://user-images.githubusercontent.com/23551496/80578355-9e64d080-8a08-11ea-92ee-069c4140d7c3.png)

**Comment by adrai** [comment]
there is no {{country}} path parser... but why not simply keep the language fully specified?
keep it: `lng: 'it-it'`

**Comment by jamuhl** [comment]
https://www.i18next.com/principles/fallback#language-fallback

**Comment by mrrobotisback** [comment]
> there is no {{country}} path parser... but why not simply keep the language fully specified?
> keep it: `lng: 'it-it'`

Because if i use it-it, backend create it and it-IT and make call for it and it-IT. but i don't know why

**Comment by adrai** [comment]
use lowerCaseLng: true

https://www.i18next.com/overview/configuration-options

![image](https://user-images.githubusercontent.com/1086194/80582174-8a23d200-8a0e-11ea-80ba-d5736d5c7989.png)

**Comment by mrrobotisback** [comment]
> lowerCaseLng: true
Yes work thanks. But why is it call api with it-it first time and second time for it ?

**Comment by adrai** [comment]
https://www.i18next.com/principles/fallback#language-fallback

**Comment by mrrobotisback** [comment]
Ok thanks a lot
