### ISSUE TITLE
Parse return type is incorrect

### ISSUE THREAD

**Issue by TrueWill** [i18next/i18next-http-backend#75]
## 🐛 Bug Report

In https://github.com/i18next/i18next-http-backend/issues/33 it's suggested to return an object from `parse` in `BackendOptions` - this works (and solved my issue - thanks), but the TypeScript types are wrong - it says `parse` returns a string.

**Comment by adrai** [comment]
Would you like to send a Pull Request to address this? Remember to add unit tests.

**Comment by TrueWill** [comment]
Done: https://github.com/i18next/i18next-http-backend/pull/76
