### ISSUE TITLE
Allow editing the languages to load if loadpath is a function

### ISSUE THREAD

**Issue by jasperfirecai2** [i18next/i18next-http-backend#78]
https://github.com/i18next/i18next-http-backend/blob/82498bd0b4dbb687a5fada5f9ce91492e1759927/i18nextHttpBackend.js#L118

It's nice that a function or promise can be passed to manage the languages and the path generation on load, but in the end all it can return is a path that will be interpolated. I would like to be able to use a function, or a path interpolation, where i can for example remove -us at the end of en-us. Since i only have a `/en` folder but browser language is set to en-us, and thus it tries to fetch a file that i know won't exist

**Comment by adrai** [comment]
You can use the fallback feature of i18next: https://www.i18next.com/principles/fallback#fallback-language
![image](https://user-images.githubusercontent.com/1086194/127984949-d6be0def-99ed-48cb-b9a5-020c35a2e3b8.png)

...and/or use a different load option: https://www.i18next.com/overview/configuration-options
![image](https://user-images.githubusercontent.com/1086194/127984905-05fb99b7-e604-49ba-a974-c8acc2f0b8e8.png)

...or simply change the served path on server side

**Comment by jasperfirecai2** [comment]
thanks you for the detailed answer. i posted this to the wrong repo. apologies for the inconvenience

**Comment by jasperfirecai2** [comment]
except the fallback only applies after the failed fetch..
![image](https://user-images.githubusercontent.com/8398131/128693539-8acaf823-df2d-4587-9dba-d2e7a2d0c819.png)
with config 
```js
{
    backend: {
      loadPath: './locales/{{lng}}/{{ns}}.json'
    },
    fallbackLng: 'en'
}
```

**Comment by adrai** [comment]
You may need to change the load option to "languageOnly": https://www.i18next.com/overview/configuration-options

**Comment by jasperfirecai2** [comment]
could've sworn I tried that before.. that works now. thanks
