### ISSUE TITLE
<Suspense> component doesn't work with i18next-http-backend custom request function

### ISSUE THREAD

**Issue by daviddaubner42** [i18next/i18next-http-backend#79]
## 🐛 Bug Report

We use the `i18next-http-backend` with a custom request function to load the translations for our React app. The custom function first tries one location, and if that fails, tries to get the files from another (viz bellow). Even though I wrapped my root component in the `<Suspense>` component as suggested by the i18next-react documentation, the components are rendered with just the translation keys, without waiting for the translations to get loaded. Do I need to do something in the custom request function to make Suspense know it should wait? 

## To Reproduce

Use a custom request function and `<Suspense>` component.
Our custom request function:

```js
const loadLocales = (options, url, payload, callback) => {
    const currentLocale = getQueryVariable({ variable: 'lng' });
    if (currentLocale && !url.match(`locale\.${currentLocale}\.json`)) {
        callback(null, { status: 404 });
        return;
    }
    new Promise((resolve, reject) => {
        fetch(url)
            .then((response) => {
                if (response.status === 404) {
                    reject();
                }
                response.text()
                    .then(locale => callback(null, { status: 200, data: locale }));
            }).catch(error => callback(error, { status: 404 }));
    }).catch(() => {
        fetch(`/localization-data/${url.match(/locale.*\.json/)[0]}`)
            .then(response => response.text())
            .then(standbyLocale => callback(null, { status: 200, data: standbyLocale }))
            .catch(error => callback(error, { status: 404 }));
    });
};
```

## Expected behavior

I expect that the fallback specified in the `<Suspense>` component will be rendered until all the translations are loaded, then the components should be rendered with translated text.

## Your Environment

- *runtime version*: node v12.10.0
- *i18next version*: 19.8.4
- *os*: Mac

**Comment by jamuhl** [comment]
are you using `useTranslation` or `withTranslation` ?

**Comment by daviddaubner42** [comment]
`useTranslation`

**Comment by adrai** [comment]
I don't think this is a problem of i18next-http-backend.... Can you please provide a reproducible example, i.e. in codesandbox?

**Comment by pcardosolei** [comment]
it is happening in a project of ours too.

**Comment by adrai** [comment]
Provide a codesandbox example or similar, please.

**Comment by pcardosolei** [comment]
Hi @adrai.

In our case it was referencing to the jest testing. I don't remember how I reached here. Using a normal configuration such as this. https://gist.github.com/kykean/952179fee07ec6aef14449c880c03b55 if will fail on the Backend when using the component **Translation** from react-i18next

```
import i18n from 'i18next';
**import Backend from 'i18next-xhr-backend';**
// TODO: needs a working custom detector for the admin URL - https://github.com/i18next/i18next-browser-languageDetector
import LanguageDetector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';

import axios from 'axios';
import helpers from './helpers';

i18n
  .use(Backend) **# fails here**
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    fallbackLng: 'en',

    debug: false,

    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
    },

    react: {
      wait: true,
    },

    ns: ['translations'],

    // remove duplicate call to en-US
    load: 'languageOnly',

    useSuspense: true,

    backend: {
      // loadPath: '/admin/{{lng}}/locales'

      // previous URL is not being interpolated with current path. build it manually - https://github.com/i18next/i18next-xhr-backend
      loadPath: function(lngs, namespaces) {
        return helpers.basePath() + '/locales';
      },

      ajax: function(url, options, callback, data) {
        axios.get(url).then(response => {
          callback(JSON.stringify(response.data), { status: '200' });
        });
      },
    },
  });

export default i18n;
```

I managed to solve it by using this Gist from @LauraBeatris. https://gist.github.com/LauraBeatris/b41e6ee76af9a56d6dd25873bbe4cecf


I can provide some logs if you want but it is not the same problem as the one described here. soz

**Comment by jamuhl** [comment]
Wondering why people mix up i18next configs from old versions...checking the documentation would help avoiding miss-configurations (there is no react.wait...and useSuspense is not on the main options but under react options).

And I'm rather sure the example here https://github.com/i18next/react-i18next/tree/master/example/test-jest works

**Comment by pcardosolei** [comment]
@jamuhl i agree. in our case i think we have lots of components can we kinda lost track about that. I will take a look. thanks
