### ISSUE TITLE
ERROR in ./node_modules/i18next-http-backend/cjs/request.js Module not found: Error: Can't resolve 'exports-loader' in '..\node_modules\i18next-http-backend\cjs'

### ISSUE THREAD

**Issue by RajeshPaycor** [i18next/i18next-http-backend#81]
am trying to build my app, it is getting error like below shown image but it is working for another application, can anyone please help me on this error

Versions:
    node = 14.17.0
and 
    "i18next": "^21.4.2",
    "react-i18next": "^11.14.2",
    "i18next-browser-languagedetector": "^6.1.2",
    "i18next-http-backend": "^1.3.1",

![image](https://user-images.githubusercontent.com/94286016/141674366-0e5bb9c9-10e6-457d-9129-3816d22c57a5.png)

**Comment by adrai** [comment]
Can you please create a reproducible example?

**Comment by RajeshPaycor** [comment]
i can't reproduce this why because in my machine there is another project is there in that its working file,
am not sure why its not working in this App

**Comment by adrai** [comment]
Sorry, without a reproducible example I can't help.
It might be some issue with your webpack configuration...
You may ask at stackoverflow.
Sorry.

**Comment by RajeshPaycor** [comment]
i found the issue why its happenning
that is because of in my webpack file if i comment below snippet its working
**new webpack.ProvidePlugin({
      fetch: "exports-loader?self.fetch!isomorphic-fetch",
    }),**
