### ISSUE TITLE
RequestResponse should have data as optional type

### ISSUE THREAD

**Issue by znikola** [i18next/i18next-http-backend#82]
## 🐛 Bug Report

`RequestResponse` interface should have `data` property as an optional type.
Currently, in case of an error, we can't pass `null` for the `data` property, but it is mentioned in your [README.md](https://github.com/i18next/i18next-http-backend#backend-options) :

```text
'res' should be an object with a 'status' property and a 'data' property containing a stringified object instance beeing the key:value translation pairs for the
  //            requested language and namespace, or null in case of an error.
```

## To Reproduce

```ts
// throws an error `Type 'null' is not assignable to type 'string'.ts(2322)`
callback(error, { data: null, status: error.status })
```

## Expected behavior

```ts
// not to throw a TS error.
callback(error, { data: null, status: error.status })
```

## Your Environment

- *runtime version*: not applicable
- *i18next version*: tha latest
- *os*: Mac, Windows, Linux

**Comment by adrai** [comment]
Would you like to send a Pull Request to address this?
