### ISSUE TITLE
Documentation for Browser JS missing

### ISSUE THREAD

**Issue by DaHoC** [i18next/i18next-http-backend#83]
## Documentation issue

I want to use i18next-http-backend in Browser (plain vanilla) JavaScript (without node ecosystem, client-side only).
Documentation about this scenario is missing, although it is implied from the project description

> i18next-http-backend is a backend layer for i18next using in Node.js, in the browser and for Deno.

that this is possible.
Furthermore, it would be nice to have minimal example code alongside the documentation for Browser JS.

**Comment by adrai** [comment]
![image](https://user-images.githubusercontent.com/1086194/147942875-6ea6c430-1de3-4dbe-bcf9-71df2cdd6aa7.png)

example: https://github.com/i18next/i18next-http-backend/blob/master/example/jquery/index.html

**Comment by DaHoC** [comment]
That was quick, thank you! :+1:
