### ISSUE TITLE
Version 1.3.1 is using vulnerable version of cross-fetch@3.1.4

### ISSUE THREAD

**Issue by p-l-l** [i18next/i18next-http-backend#84]
## 🐛 Bug Report

Version 1.3.1 is using `cross-fetch@3.1.4` that is using a vulnerable version of module `node-fetch`.
 ![image](https://user-images.githubusercontent.com/23360637/150541717-573bf093-a216-4dd2-9268-23e7184acf20.png)

A recent version of `cross-fetch` addresses this issue:
https://github.com/lquixada/cross-fetch/releases/tag/v3.1.5

Requesting to upgrade to `cross-fetch@3.1.5`

**Comment by adrai** [comment]
Thank you, v1.3.2 updates all dependencies.
