### ISSUE TITLE
customLoadPath function run per language / namespace to allow caching at asset-level

### ISSUE THREAD

**Issue by dalevfenton** [i18next/i18next-http-backend#86]
## 🚀 Feature Proposal

We serve our language assets as static json files out of a CDN. We want to be able to have the content-hash of each asset used for cache invalidation on an individual asset level. (i.e. we add or update a value in `en/common.json` it will change the asset name from `en/common.abcde.json` to `en/common.defgh.json`, but other asset files like `en/login.12434.json` will stay the same.

Using the `loadPath` we are able currently to only set a static hash across all our assets since they all use the same interpolation string (i.e. `https://cdn.com/lang/{{lng}}/{{ns}}.qwery.json`). We would like to be able through `loadPath` or another option to return a unique `loadPath` per `language` and `namespace`.

So if `loadPath` returns a string it would continue to be passed directly to `this.services.interpolator.interpolate`, but if `loadPath` returns a map of strings it should try to load each language / namespace combination from the map based on a lookup of language and namespace

Alternatively it could have an extra option called customLoadPaths, that could allow us to pass in something like
```
{
     "en": { "common": "/lang/{{lng}}/{{ns}}.abcdef.json", "login": "/lang/{{lng}}/{{ns}}.ghjkl.json" },
     "es": { "common": "/lang/{{lng}}/{{ns}}.qwert.json", "login": "/lang/{{lng}}/{{ns}}.yuiop.json" },
}
```
## Motivation

Allow us to setup cache invalidation on a per-asset level instead of having to invalidate all resources if any of them change.

## Example

We would pass a config object or function to the options for the plugin that would allow us to specify a custom `loadPath` per language and namespace. Ideally, `loadPath` could remain the same and then `customLoadPaths` could be a function with signature `(language: string, namespace: string) => string` or a config object: `{ [K in Languages]?: { [N in Namespaces]?: string } }`, if the function or object fails to provide a string for interpolation, then the normal `loadPath` could be used or the typical error / fallback behavior can be performed

**Comment by adrai** [comment]
Currently the loadPath option can be a function, so this should already be possible right?

https://github.com/i18next/i18next-http-backend#backend-options
<img width="739" alt="image" src="https://user-images.githubusercontent.com/1086194/155166986-0b7d5107-80e3-4d67-85e0-55378ad74735.png">

https://github.com/i18next/i18next-http-backend/blob/master/test/http.spec.js#L97

**Comment by dalevfenton** [comment]
you're right, I thought it only ran this once with all languages and all namespaces, but the arrays are there for multi-loading and it does run the function per-asset needed so it works for what we need

**Comment by MetaMmodern** [comment]
Hi @dalevfenton , can you please share your `loadPath` function? I'm interested in how you generate the contenthash, using what.
I have a webpack project and was just going to use CopyPlugin to copy translations from public to dist with contenthash, but I don't know how I would get then the same hash in loadPath.

**Comment by MetaMmodern** [comment]
Very nice, @dalevfenton , thank you
After writing to you I wrote a similar code for webpack, but using file-loader and a bit simpler, but that works as well.

But your part with i18n is a bit confusing, you use backendResources as local development, and those contain imported jsons. However, when you're in prod, you have a backend function, loadPath, which grabs resource files by url. How did you tell that function, that your lang resources will have contenthash in the name? Or, how soes i18n understand, that translation files will have contenthash?

I'm gonna make a suggestion: probably the trick is that it gets a list of files from certain language folder, and since you have only one file in that folder you just return it. Is that right?

**Comment by dalevfenton** [comment]
@MetaMmodern the trick is that the contents of the json files are replace during the build by the webpack asset loader with the value returned by the `generator` in the loader

as a result after a build it will have a value like below which will match the names of the assets that are hosted in our static directory, the content hash automatically busts the cached asset on the client whenever the contents of those files change based on the content of the source file:

```
const backendResources = {
  resources: {
    en: {
      common: lang/en/common.12345.json,
    },
    es: {
      common: lang/es/common.54321.json,
    },
  },
};
```

**Comment by MetaMmodern** [comment]
@dalevfenton oooh now I see, I wasn't reading carefully, you load THIS when you have prod deployment
Amazing, that's exactly what I was trying to achieve today, but the path was not clear. Now I can code with confidence that this is possible
Thank you!!!

One last
