### ISSUE TITLE
try to load it-IT language

### ISSUE THREAD

**Issue by mredodos** [i18next/i18next-http-backend#87]
hi, i have strange behavior back end search and load default language EN (is ok) and IT (is ok) but try to load it-IT language. why ? is normal? 

![image](https://user-images.githubusercontent.com/42175654/157294762-5b32979f-5265-4dda-83d4-ac7cf45059ca.png)

best regards

**Comment by adrai** [comment]
Set the `load` option to `languageOnly`

https://www.i18next.com/overview/configuration-options

`i18next.init({ load: 'languageOnly' })`

**Comment by mredodos** [comment]
thx!

**Comment by codertushar** [comment]
For me, below worked:
![image](https://github.com/i18next/i18next-http-backend/assets/59651629/f4fcddbf-4218-42d3-8e2a-42feb4be139b)
as I have locales folders like:
<img width="46" alt="image" src="https://github.com/i18next/i18next-http-backend/assets/59651629/c6b62510-bc39-4d53-8d4a-76358ae6878b">
