### ISSUE TITLE
Hydration Error on page reload with next 12 + react 18

### ISSUE THREAD

**Issue by Christian-Schoenlein** [i18next/i18next-http-backend#91]
## 🐛 Bug Report

When using client side translation in development running `next dev` on page refresh react throws the following error:
`Error: Text content does not match server-rendered HTML.` 

The following errors appear in the console: `Text content did not match. Server: "Hello World" Client: "hello_world"`

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/99257912/171315322-998f31e7-ca87-4e4d-985d-8a07cf8ea809.png">

Error message running production server `next build` and `next start`.
<img width="538" alt="image" src="https://user-images.githubusercontent.com/99257912/171317005-ad37d45c-14db-47a3-a422-a8c85d6be650.png">

## To Reproduce

A [Github Repository](https://github.com/Christian-Schoenlein/next-18next-backend-hydration-error) reproducing the bug.

The same bug can be reproduced with the [next example](https://github.com/i18next/i18next-http-backend/tree/master/example/next) and `react` & `react-dom` version 18.1.0.

## Expected behavior

No hydration error.

## Your Environment

- Runtime: Node.js v16.14.0, Chromium v102, Safari v15.5
- next-i18next version: 11.0.0
- OS: MacOS v12.4

**Comment by adrai** [comment]
Yes, that's the nature of client side loaded translations...
On server side, the translations are ready, but on client side they need first to be loaded. So they are not yet ready on the first render loop.
That's why in the example it is checked for the ready flag and if not ready a fallback will be rendered: https://github.com/i18next/i18next-http-backend/blob/master/example/next/pages/client-page.js#L11
btw: normally it is only a warning, not an error: "Warning: Expected server HTML to contain a matching text node for "loading translations..." in <div>."
<img width="829" alt="image" src="https://user-images.githubusercontent.com/1086194/171335387-99e36f24-545c-4c39-8d7b-dedc119d9314.png">

**Comment by Christian-Schoenlein** [comment]
I am aware of the pattern but I was trying to translate the navbar & footer of my app using a Layout which cannot use SSR or SSG since it's not a NextPage.

I also tried using the ready flag which doesn't help because it doesn't solve the problem that whats rendered on the server isn't the same as what's rendered on the client initialy.

But I found a solution instead of having the translation in the return statement directly I moved it in a useEffect which only gets executed on the client side and stored the translation in a useState value. On the server the useEffect doesn't run and the translated string is undefined and on the client it will be undefined for the first render because the translation file is not available yet since its async.

### Before with hydration error

<img width="428" alt="image" src="https://user-images.githubusercontent.com/99257912/171455954-27b9d275-7d69-4025-b22b-1f615295da4b.png">

### After with useEffect & useState

<img width="735" alt="image" src="https://user-images.githubusercontent.com/99257912/171456009-884bb30b-9476-4202-a995-a4aa6ff432da.png">

**Comment by isaachinman** [comment]
> which cannot use SSR or SSG since it's not a NextPage

That is simply not true. You just need to pass the appropriate namespace via your page itself, or put it as `defaultNS`.

**Comment by Christian-Schoenlein** [comment]
> That is simply not true. You just need to pass the appropriate namespace via your page itself, or put it as defaultNS.

In Next.js Layouts are located inside the custom app component which is not a next page.

From the docs:
> Inside your layout, you can fetch data on the client-side using useEffect or a library like [SWR](https://swr.vercel.app/). Because this file is not a [Page](https://nextjs.org/docs/basic-features/pages), you cannot use getStaticProps or getServerSideProps currently.

So you can't just pass down the namespace because the layout lives above every single next page and wraps around them.

**Comment by isaachinman** [comment]
I can assure you it's possible.

**Comment by Zerebokep** [comment]
A solution for this problem should be included in the readme file, as the example doesn't work (at least not without errors).

**Comment by isBatak** [comment]
With React 18 you can enable `useSuspense` option
```
/**
 * @type {import('i18next').InitOptions & Pick<import('next').NextConfig, 'i18n'>}
 */
module.exports = {
	backend: {
		backendOptions: [
			{ expirationTime: 60 * 60 * 1000 },
			{
				/* loadPath: 'https:// somewhere else' */
			},
		], // 1 hour
		backends: typeof window !== 'undefined' ? [LocalStorageBackend, HttpBackend] : [],
	},
	i18n: {
		defaultLocale: 'en-US',
		locales: ['en-US'],
	},
	serializeConfig: false,
	use: typeof window !== 'undefined' ? [ChainedBackend] : [],
	react: {
		useSuspense: true,
	},
};
```

**Comment by thienna** [comment]
any update?

**Comment by bryantobing12** [comment]
why this is closed with no solution? i think this is related to the rename of `hydrate` functionality in react 18 to `hydrateRoot` https://nextjs.org/docs/messages/react-hydration-error

**Comment by bryantobing12** [comment]
> With React 18 you can enable `useSuspense` option
> 
> ```
> /**
>  * @type {import('i18next').InitOptions & Pick<import('next').NextConfig, 'i18n'>}
>  */
> module.exports = {
> 	backend: {
> 		backendOptions: [
> 			{ expirationTime: 60 * 60 * 1000 },
> 			{
> 				/* loadPath: 'https:// somewhere else' */
> 			},
> 		], // 1 hour
> 		backends: typeof window !== 'undefined' ? [LocalStorageBackend, HttpBackend] : [],
> 	},
> 	i18n: {
> 		defaultLocale: 'en-US',
> 		locales: ['en-US'],
> 	},
> 	serializeConfig: false,
> 	use: typeof window !== 'undefined' ? [ChainedBackend] : [],
> 	react: {
> 		useSuspense: true,
> 	},
> };
> ```

with `useSuspense` set to true. somehow it breaks some assets used in nextjs, like the use of `next/image`, `favicon`, etc

@isBatak

**Comment by isBatak** [comment]
@bryantobing12 how can that be connected?
Maybe `next/image` breaks when it's wrapped in `<Suspense>`. Could you check that in isolation?

**Comment by bryantobing12** [comment]
@isBatak  I'm not sure. next/link SPA seems to break as well

**Comment by bryantobing12** [comment]
wrapping my top component with `<Suspense>` fix the issue

```ts
<React.Fragment>
  <React.Suspense fallback={<div>Loading</div>}>
    <NProgress stopDelayMs={0} />
    <Component {...pageProps} />
  </React.Suspense>
</React.Fragment>
```

**Comment by ObaidQatan** [comment]
I managed to solve this by preventing any client translations from being returned before the server-client cycle completes. Something like `if (!hasRendered) return null`, but it's kinda exhaustive to put this line before the return statement of every client component. Instead, I've adjusted my `useTranslations` hook a bit, making it return only the same values that were passed initially.

This's how `useTranslations` return statement looked like (Hydration Error):
```ts
return {
    translation: (key: string) => data?.[key] ?? key,
    loading: isLoading,
    locale: loc,
    dict: data ?? {}, // NOTE: This is useful for passing translations as a prop, and for debugging.
    refetchTranslations: refetch,
  };
```
Added Lines (to the hook itself, not components):
```ts
  const [hasRendered, setHasRendered] = React.useState(false);

   React.useEffect(() => {
    setHasRendered(true);
  }, []);
```
```ts
if (!hasRendered) {
    return {
      translation: (key: string) => key,
      loading: true,
      locale: loc,
      dict: {},
      refetchTranslations: refetch,
    };
  }
```
You may also return `null` if not yet rendered if you'd use the `translations` function accordingly in your code.
