### ISSUE TITLE
Fix for security issues in Synk

### ISSUE THREAD

**Issue by nandeshwarshubh** [i18next/i18next-http-backend#93]
Hi,

The following issue was reported in Snyk for i18next-http-backend. Is there a roadmap to update the following dependency to fix the issue?

[Snyk i18next-http-backend issues](https://app.snyk.io/test/npm/i18next-http-backend)

Regular Expression Denial of Service (ReDoS) - i18next-http-backend@1.4.1 › cross-fetch@3.1.5 › node-fetch@2.6.7

**Comment by adrai** [comment]
This needs first to be addressed in [cross-fetch](https://github.com/lquixada/cross-fetch) (@lquixada) and probably also wait for the fixed v2 release in [node-fetch](https://github.com/node-fetch/node-fetch/pull/1605) (@westy92)

**Comment by westy92** [comment]
I emailed Snyk last night about this issue. As far as I can tell, it was introduced in node-fetch 3.1.0 and doesn't affect 2.x.

**Comment by adrai** [comment]
> I emailed Snyk last night about this issue. As far as I can tell, it was introduced in node-fetch 3.1.0 and doesn't affect 2.x.

if it's the case, this is not an issue for i18next-http-backend
