### ISSUE TITLE
Client side loading randomly fails...

### ISSUE THREAD

**Issue by MoOx** [i18next/i18next-http-backend#98]
## 🐛 Bug Report

Hi, I followed carefully the NextJS example and have a weird issue: the translation on the client randomly fails (and instead I have translations keys).
You can see this in production here https://jokerie.com/@/max__carre
If you check the top right corner, you have a purple button `Se connecter` that sometimes shows `Header-SignIn`.
Do you have any clue about this behaviour ?
FYI, my project use vercel with a standard next config.

## To Reproduce

My project is private but I can add you to the project if you have time to check.

## Expected behavior

I do not expected a "random" failure...

One thing I am not sure about is the last "Alternative usage": I don't really understand why there is no need for "ready".
I checked the code from the example carefully but didn't notice a thing that I could have missed...

## Your Environment

- *runtime version*: node --version && npm --version v14.18.3, 8.6.0
- *browser*: latest Safari & Chrome, same issue.
- *i18next version*: 
   ```
    "i18next-chained-backend": "3.1.0",
    "i18next-http-backend": "1.4.4",
    "i18next-localstorage-backend": "3.1.3",
    "next": "12.3.1",
    "next-i18next": "12.1.0",
  ```

- *os*: macOS

**Comment by adrai** [comment]
idk... need to see some code or a minimal reproducible example

**Comment by MoOx** [comment]
Ok. I wasn't able to reproduce outside production. Really annoying.
I switched to another i18n solution. Thanks anyway.

**Comment by eloyra** [comment]
@MoOx I'm having a similar issue. What solution did you use in the end? Did it work better?

**Comment by MoOx** [comment]
@eloyra next-intl is working great.

**Comment by jamuhl** [comment]
my guess...missing useTranslation (eg. a component that just uses Trans but has no useTranslation hook)

**Comment by adrai** [comment]
@eloyra a minimal reproducible example will help to investigate.

**Comment by eloyra** [comment]
Hey, sorry for the delay, I was cought up in other stuff.
In the end I decided to move away from `next-i18next` and I'm using `next-translate`, which works as expected.
I will try to create a minimal example in the following days, because I like this library better and it would be great getting it to work.
